### ISSUE TITLE
git dependency causing install issue

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#1]
@brycekahle, using git to grab the node packages is a breaking change for users where some of them do not have **git** installed and unable to install the new **particle-cli**. Can we do something about it instead of getting them to install more tools?

**Comment by brycekahle** [comment]
Definitely. We can get that fixed. 



—
Bryce KahleSenior Software Engineer

https://spark.io/

**Comment by brycekahle** [comment]
One down, waiting for a PR merge and and npm publish on the other one.

**Comment by brycekahle** [comment]
All git dependencies removed.
