### ISSUE TITLE
particle setup doesnt work without a driver on Windows 10

### ISSUE THREAD

**Issue by dwcares** [spark/particle-cli#10]
Windows 10 has a usb serial driver so you didn't need to install the Windows Driver. I made a change that made this work with the spark core by checking the vendor id right in the pnpid string. This doesn't work with the photon since there's a new vendor and product id for the photon.

**Comment by dmiddlecamp** [comment]
bump :)

**Comment by kennethlimcp** [comment]
Photon on Mac: 

```
{ comName: '/dev/cu.usbmodem1411',
  manufacturer: 'Spark Devices',
  serialNumber: '00000000050C',
  pnpId: '',
  locationId: '0x14100000',
  vendorId: '0x2b04',
  productId: '0xc006' }
```

Spark core on Mac:

```
{ comName: '/dev/cu.usbmodem1411',
  manufacturer: 'Spark Devices     ',
  serialNumber: '8D6A41694854',
  pnpId: '',
  locationId: '0x14100000',
  vendorId: '0x1d50',
  productId: '0x607d' }
```

Photon on Windows:

```
{ comName: 'COM9',
  manufacturer: 'Photon',
  serialNumber: '',
  pnpId: 'USB\\VID_2B04&PID_C006\\00000000050C',
  locationId: '',
  vendorId: '',
  productId: '' }
```

Spark Core on Windows XP:

```
{ comName: 'COM9',
  manufacturer: 'Photon',
  serialNumber: '',
  pnpId: 'USB\\VID_2B04&PID_C006\\00000000050C',
  locationId: '',
  vendorId: '',
  productId: '' }
```

**Comment by harrisonhjones** [comment]
@kennethlimcp I see "Spark Devices" as my manufacturer on my cores in Windows. How did you generate the above output?

**Comment by dwcares** [comment]
On windows 10, without the drvier it doesn't emit the manufacturer, just the pid/vid.

**Comment by kennethlimcp** [comment]
@emilyrose, can be closed with https://github.com/spark/particle-cli/commit/7fc5b338a70d0ff754a9eff023a5c09eef5ac178

**Comment by dwcares** [comment]
Has anyone tried a photon on windows 10 without a driver? Not working for me

**Comment by emilyrose** [comment]
@dwcares I haven't! If https://github.com/spark/particle-cli/commit/7fc5b338a70d0ff754a9eff023a5c09eef5ac178 isn't a fix we should definitely figure something out. I wonder if @kennethlimcp has any input here.

**Comment by kennethlimcp** [comment]
@dwcares the fix i sent is similar to what you wrote? I'm not sure what the device profile looks like without a driver though. Can you make sure your `particle-cli` is the latest?

**Comment by brycekahle** [comment]
I can give this a try tonight.

**Comment by brycekahle** [comment]
Confirmed not working on Windows 10. The issue is that the manufacturer is reported as Microsoft, not `Particle` or `Spark`. Here is the output from `node-serialport`:

```
{ comName: 'COM3',
    manufacturer: 'Microsoft',
    serialNumber: '',
    pnpId: 'USB\\VID_2B04&PID_C006\\00000000050C',
    locationId: '',
    vendorId: '',
    productId: '' }
```

**Comment by dwcares** [comment]
The fix looks good. I'll try it ASAP. Thank you
