### ISSUE TITLE
`particle setup` prompts for Mac OS X system password three times, every time

### ISSUE THREAD

**Issue by pomplesiegel** [spark/particle-cli#101]
![image](https://cloud.githubusercontent.com/assets/1450352/9420085/e0ed6518-482f-11e5-8e7e-4c6e3ed931c1.png)

`particle setup` requires the user enter the Mac OS X system password three times, back to back throughout each setup of a Photon for `networksetup`.

**Comment by pomplesiegel** [comment]
@brycekahle, is this fix pulled into the current CLI? I'm still having the same issue on Mac OS X, running 10.10.4.

**Comment by brycekahle** [comment]
Yes, it is part of the released version. What terminal are you using? I wonder if that has something to do with it.

**Comment by pomplesiegel** [comment]
Oh, I see. I'm using OS X's native terminal.

**Comment by brycekahle** [comment]
You get prompted 3 times still? I would expect once, but not 3 times.

**Comment by pomplesiegel** [comment]
Currently seeing 3 times, every time. Running 1.8.3 in the native terminal. Installed via homebrew -> npm -> particle-cli
