### ISSUE TITLE
Cryptic error message for duplicate device names

### ISSUE THREAD

**Issue by jme783** [spark/particle-cli#104]
```
? What would you like to call your photon? dontTouchMahCore
! Error naming your photon:  { ok: false, code: 403, errors: [ {} ] }
```

This is the output when I already have a device named `dontTouchMahCore`

**Comment by kennethlimcp** [comment]
Is there or does the endpoint allow us to check for duplicate names? `particle list` seems to be an expensive call though it's still pretty speedy.

**Comment by brycekahle** [comment]
The list endpoint would actually be faster than checking an individual device because the individual device endpoint actually talks to the device.

**Comment by brycekahle** [comment]
It looks like the API isn't providing a good error message here. Moving the issue there.
