### ISSUE TITLE
Dashes now not allowed in device names?

### ISSUE THREAD

**Issue by pomplesiegel** [spark/particle-cli#110]
Strange behavior when attempting to claim/rename a Photon with a name containing dashes, using the latest cli. 

For example, if I attempt to claim or rename a photon to the name
`GX-LT-0001`, cli returns the message
````Failed to rename <device name>, server said undefined````

but when calling `particle list` there is now a claimed photon called `GX_LT_0001` (underscores)

Is this a bug or an intentional restriction? If it's the latter, please revert this change. We have more than one hundred prototypes in the field with SNs containing dashes.

**Comment by brycekahle** [comment]
Thanks for the bug report. We did start doing some device name sanitizing, but it shouldn't be replacing dashes. I'll get that fixed and report back here. Sorry!

**Comment by pomplesiegel** [comment]
Great, thank you!

**Comment by brycekahle** [comment]
This should be fixed now. Sorry about that @pomplesiegel

**Comment by pomplesiegel** [comment]
Hey @brycekahle, when attempting to rename a Photon to a new name containing dashes, i'm getting back

````Failed to rename <Photon name>, server said [ {} ]````

**Comment by kennethlimcp** [comment]
Hmm... it worked for me:

```
KENMBP:~ kennethlimcp$ particle device rename Pho1 pho-1
Renaming device Pho1
Successfully renamed device Pho1 to: pho-1
```

**Comment by brycekahle** [comment]
What is the name you are trying?

**Comment by pomplesiegel** [comment]
````GL-EA-9002````

**Comment by pomplesiegel** [comment]
Just tried ````particle device rename UART_Test1 GL-EA-9002````

**Comment by brycekahle** [comment]
Can you try using the device id instead of `UART_Test1`?

**Comment by pomplesiegel** [comment]
OK, Just tried, and same result

**Comment by brycekahle** [comment]
Can you try hitting the API directly using `curl` and pasting the output (sanitized of your access token of course)? If you need the command, let me know.

**Comment by pomplesiegel** [comment]
Resolved w/ @brycekahle's help
