### ISSUE TITLE
Support I2C devices

### ISSUE THREAD

**Issue by BrianGenisio** [spark/particle-cli#111]
This will be in conjunction with a VoodooSpark update as well.  I'm starting work on this, but I wanted to create an issue to track questions and conversations here.

**Comment by BrianGenisio** [comment]
Looking through firmata.js and J5, I see that J5 only uses the newer i2c prefixed API calls on the IO layer. There are a handful of other calls (i2cRequest, sendI2CConfig, sendI2CWriteRequest, and sendI2CReadRequest) which are not used by J5. Are these deprecated? Or should a complete IO implementation for particle-io include these other functions as well?

**Comment by BrianGenisio** [comment]
I see that the [Tessel-io](https://github.com/rwaldron/tessel-io/blob/master/lib/tessel.js) does implement the old functions, and does argument massaging to make sure the two interfaces work with the same, aliased function.

I'll just use this pattern.

**Comment by emilyrose** [comment]
Hey @BrianGenisio,

Although I am also super interested in Johnny-five as it relates to Particle, I'm not sure what the intent of this issue is. Would you mind clarifying what exactly it is you'd like to see change in the Particle CLI?

**Comment by BrianGenisio** [comment]
I'm a jerk.  Meant to open this in `particle-io` not `particle-cli`.  Sorry!

**Comment by emilyrose** [comment]
@BrianGenisio hey, that doesn't even come close to making you a jerk! :smile_cat: 

I was just confused and thought I was maybe missing something, but this makes more sense.

I definitely need to make the time to revisit J5 on Particle!
