### ISSUE TITLE
`Token error: Problem requesting variable: Timed out`

### ISSUE THREAD

**Issue by pomplesiegel** [spark/particle-cli#113]
````sh
Token error: Problem requesting variable: Timed out
````

Is this a normal timeout error due to a device being offline, or is this something else?
This occurs for only one Photon on our account, and the device name is correct. 
Our query is to `get` a variable which definitely exists 
````sh
particle get <deviceName> swVersion
````
This command works for other online Photons.

**Comment by brycekahle** [comment]
That appears to be a misleading error message. It has nothing to do with the token. `Timed out` is the real error.

**Comment by pomplesiegel** [comment]
OK, great! Just thought I'd bring it to your attention, as I wondered why the word token appeared in this at all. Sounds like only the error message needs to be changed. Thanks!
