### ISSUE TITLE
CLI fails to find Photon AP even though computer sees it

### ISSUE THREAD

**Issue by towynlin** [spark/particle-cli#118]
Elite member @ScruffR has reported this on Windows with particle-cli version 1.6.9.

For him `particle wireless list` and `particle wireless monitor` both fail to find the AP, but he can manually connect the computer to the Photon AP and get responses using the setup protocol.

**Comment by brycekahle** [comment]
Can you run `netsh wlan show networks mode=Bssid` and post the output here?

**Comment by ScruffR** [comment]
As written in my original post on slack I even can connect my Windows 8.1Pro 64bit (with Broadcom 802.11abgn Wireless SDIO Adapter BCMSDH43xx) to the Photon AP and download the "Hello-Message" from the device.
```
SSID 2 : Photon-U8BS
    Netzwerktyp             : Infrastruktur
    Authentifizierung       : Offen
    Verschlüsselung         : Keine
    BSSIDD 1                 : 6c:0b:84:1b:22:92
         Signal             : 59%
         Funktyp         : 802.11n
         Kanal           : 11
         Basisraten (MBit/s)   : 1 2 5.5 11
         Andere Raten (MBit/s) : 6 9 12 18 24 36 48 54
```

All my Photons (with 0.4.4) act the same.

**Comment by brycekahle** [comment]
Aha, so `node-wifiscanner2` isn't expecting German in the output. I'll see if I can add some locale switching to it.

**Comment by brycekahle** [comment]
@ScruffR do you still have this problem? https://github.com/spark/particle-cli/commit/78e613a70beb0c3c9372ca64109299500d1d5a72 introduced locale support for the wifi scanning.

**Comment by ScruffR** [comment]
@brycekahle, uhh sorry, I thought I had replied on to your post back in September already (when it didn't work), but unfortunately it still doesn't work 

I'm using 
CLI v1.9.0
node v4.2.4
npm 2.14.12

I've tested on 
Lenovo Thinkpad Yoga S15, Win 10 Pro 64bit German and
Lenovo Thinkpad Tablet 10, Win 8.1 Pro 64 bit German

**Comment by ScruffR** [comment]
In addition to the original issue I even have another problem, probably rooting in the same underlying cause.
When I try `particle setup` or `particle serial wifi` and let CLI scan for available networks, I always get 
```text
C:\Users\Andy>particle serial wifi
? Should I scan for nearby Wi-Fi networks? (Y/n) y
? Should I scan for nearby Wi-Fi networks? Yes
? Uh oh, no networks found. Try again? Yes
? Uh oh, no networks found. Try again? Yes
? Uh oh, no networks found. Try again? Yes
? Uh oh, no networks found. Try again? (Y/n)
```
On both machines again.

**Comment by brycekahle** [comment]
Definitely same underlying issue. Would you mind cloning https://github.com/spark/node-wifiscanner, adding `console.log(stdout);` above https://github.com/spark/node-wifiscanner/blob/master/lib/netsh.js#L68 and then running this simple program from the root repo directory? Please paste the results here or email/PM them to me. Thanks!

```
var scanner = require('./lib/wifiscanner');
scanner.scan(function(err, networks) {
  console.log(err, networks);
});
```

**Comment by ScruffR** [comment]
This is what I get
```text
C:\Particle\.git\node-wifiscanner>testScan.js
module.js:340
    throw err;
    ^

Error: Cannot find module 'os-locale'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Particle\.git\node-wifiscanner\lib\wifiscanner.js:5:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by brycekahle** [comment]
Ah, I forgot a step. Run `npm install` from the repo dir and then run the program again. Thanks!

**Comment by ScruffR** [comment]
Doh', I could have thought of that

```text

Schnittstellenname : WiFi
Momentan sind 7 Netzwerke sichtbar.

SSID 4 :
    Netzwerktyp             : Infrastruktur
    Authentifizierung       : WPA2-Personal
    Verschl?sselung         : CCMP
    BSSIDD 1                 : 00:23:be:30:49:0e
         Signal             : 46%
         Funktyp         : 802.11n
         Kanal           : 6
         Basisraten (MBit/s)   : 1 2 5.5 11
         Andere Raten (MBit/s) : 6 9 12 18 24 36 48 54

SSID 5 : KBH4htor#
    Netzwerktyp             : Infrastruktur
    Authentifizierung       : WPA2-Personal
    Verschl?sselung         : CCMP
    BSSIDD 1                 : 00:23:be:30:49:0e
         Signal             : 39%
         Funktyp         : 802.11n
         Kanal           : 6
         Basisraten (MBit/s)   : 1 2 5.5 11
         Andere Raten (MBit/s) : 6 9 12 18 24 36 48 54

SSID 6 : KBH4htor!
    Netzwerktyp             : Infrastruktur
    Authentifizierung       : WPA2-Personal
    Verschl?sselung         : CCMP
    BSSIDD 1                 : 00:8e:f2:77:a5:53
         Signal             : 72%
         Funktyp         : 802.11n
         Kanal           : 6
         Basisraten (MBit/s)   : 1 2 5.5 11
         Andere Raten (MBit/s) : 6 9 12 18 24 36 48 54
```
This `Verschl?sselung` would actually be `Verschlüsselung`

**Comment by brycekahle** [comment]
@ScruffR thanks. That helps a lot!

**Comment by brycekahle** [comment]
Lets add some more debug output. Can you add `console.log(info);` above https://github.com/spark/node-wifiscanner/blob/master/lib/netsh.js#L56 and report the output? Thanks.

**Comment by ScruffR** [comment]
Of course, an this time I had my tab even connected to the Photon AP ;-)

```text

SSID 4 : Photon-C6MN
    Netzwerktyp             : Infrastruktur
    Authentifizierung       : Offen
    Verschl?sselung         : Keine
    BSSIDD 1                 : 6c:0b:84:59:3c:c4
         Signal             : 75%
         Funktyp         : 802.11n
         Kanal           : 11
         Basisraten (MBit/s)   : 1 2 5.5 11
         Andere Raten (MBit/s) : 6 9 12 18 24 36 48 54

SSID 5 :
    Netzwerktyp             : Infrastruktur
    Authentifizierung       : WPA2-Personal
    Verschl?sselung         : CCMP
    BSSIDD 1                 : 00:23:be:30:49:0e
         Signal             : 79%
         Funktyp         : 802.11n
         Kanal           : 6
         Basisraten (MBit/s)   : 1 2 5.5 11
         Andere Raten (MBit/s) : 6 9 12 18 24 36 48 54


{ signal_level: -60.5 }
null []
```

**Comment by brycekahle** [comment]
Hmm. So bizarre. I can take your output and run it through the test and it works great. What version of node are you running?

**Comment by ScruffR** [comment]
node 4.2.4

**Comment by brycekahle** [comment]
Hmm. How comfortable are you with node? Do you think you could debug this issue with some `console.log` debugging? The issue should be within https://github.com/mauricesvay/node-wifiscanner/blob/master/lib/netsh.js

**Comment by ScruffR** [comment]
I'll have a stab.

**Comment by ScruffR** [comment]
@brycekahle, one thing I already found out is that the localized terms don't get pushed to `parseNetsh()` 
```
Terms:
{ SSID: 'SSID',
  BSSID: 'BSSID',
  Signal: 'Signal',
  Channel: 'Channel' }  // <-- should be Kanal
Fields:
{ mac: /^BSSID \d+\s*:\s*(.*)/,
  ssid: /^SSID \d+\s*:\s*(.*)/,
  signal_level: /^Signal\s*:\s*(\d+)/,
  channel: /^Channel\s*:\s*(\d+)/ }   // <-- should be "Kanal" 
```
 And hence the channel fields are not filled.

**Comment by ScruffR** [comment]
@brycekahle, as it seems the problem lies in 'os-locale'.

This is the "call stack" 
```text
*** if (cache || getEnvLocale() || !execFileSync || opts.spawn === false) ***
*** module.exports.sync = function (opts) *** opts={ spawn: false }
*** getEnvLocale(env) *** env=undefined
*** getLocale(str) *** str=undefined
*** fallback() ***
cache: en_US
```

**Comment by brycekahle** [comment]
@ScruffR does it work if you change `spawn` to `true` here? https://github.com/spark/node-wifiscanner/blob/master/lib/wifiscanner.js#L44

**Comment by ScruffR** [comment]
OK, with `true` I at least get the correct `locale`
```text
*** if (cache || getEnvLocale() || !execFileSync || opts.spawn === false) ***
*** getEnvLocale *** env=undefined
*** getLocale *** str=undefined
*** fallback ***
**** never reaches this ****
Win32
Locale
0c07


lcidCode:  3079
Cache:  de_AT
fullLocale: de_AT
osLocale:
{ [Function] sync: [Function] }
Locale:
de_AT
Path: ../locales/en.json
Terms:
{ netsh:
   { SSID: 'SSID',
     BSSID: 'BSSID',
     Signal: 'Signal',
     Channel: 'Channel' },
  airport:
   { BSSID: 'BSSID',
     RSSI: 'RSSI',
     CHANNEL: 'CHANNEL',
     HT: 'HT',
     SECURITY: 'SECURITY',
     CC: 'CC' },
  iwlist:
   { Cell: 'Cell',
     Address: 'Address',
     ESSID: 'ESSID',
     Channel: 'Channel',
     'Signal level': 'Signal level',
     'Scan completed :': 'Scan completed :',
     'Interface doesn\'t support scanning.': 'Interface doesn\'t support scanning.' } }
```
But the terms are not selected for mine, since I'm in Austria (AT) and not Germany (DE).
