### ISSUE TITLE
Setup hangs after manual wifi input

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#122]
I think the issue is that i am already connected to the AP of the Photon and was prompted to switch back to a connection with internet and led to this failing.

```
? Would you like to manually enter your Wi-Fi network configuration? Yes
? Please enter the SSID of your Wi-Fi network: limfamily
? Please enter your Wi-Fi network password (leave blank for none): 1234567890
? Please select the security used by your Wi-Fi network: WPA2
> Here's what we're going to send to the Photon:

> Wi-Fi Network: limfamily
> Password: xxxxx
> Security: WPA2

? Would you like to continue with the information shown above? Yes

> Obtaining device information...
```

**Comment by brycekahle** [comment]
So you were connected to the Photon AP at this point? You should be, `Obtaining device information` is attempting to talk to the Photon.

**Comment by kennethlimcp** [comment]
Yes it just stays at `Obtaining device information` forever

**Comment by brycekahle** [comment]
Ok. We probably need a timeout of some sort there.

**Comment by hintron** [comment]
@brycekahle As of version 1.12.0, this problem still exists for me. Maybe the new command timeouts don't affect this repeating behavior.

**Comment by brycekahle** [comment]
@hintron particle-cli has not been updated to use the newer versions of `softap-setup-js` yet which is why you still see the problem and this issue is still open.

**Comment by dialex** [comment]
As of today, this problem is still happening to me (right now).
Is there any workaround?

**Comment by monkbroc** [comment]
The issue above was when your laptop was connected to the Photon WiFi network before running the `particle setup` command. Does it work for you if you are connected to your regular WiFi network before doing `particle setup`?

**Comment by dialex** [comment]
1. I'm connected to my office wifi.
2. I connect the Internet Button via USB. Green light is blinking.
2. I press `SETUP` for 3 seconds and blue light is bliking.
3. I run `particle setup`.
4. It detects my Photon and confirm the setup.
 - I select to automatically scan wifi networks. Switches to Photo wifi.
 - Scanning takes ages and I give up.

If I select to manually add wifi networks. It automatically switches to the Photon wifi and then loops on that obtaining device. I'm blocked 😕

**Comment by monkbroc** [comment]
Thanks for the info. Sorry you're blocked on the setup. You can do `particle serial wifi` with the Photon connected by USB and in listening mode (bllinking blue). This will set up Wi-Fi on your device. Did you already claim this Photon to your account?

**Comment by dialex** [comment]
Thank you so much for helping me with the process.

Yes, I already claimed the particle using my home wifi. And it worked kind of straightforward.

After doing the `particle serial wifi`, it worked! With that command, particle found the available networks (as expected) and I just had to select and type in the password. It's weird because yesterday I also tried that command and it didn't...

Anyway, thank you so much for helping me. I hope this is useful to someone else.

**Comment by NinjaneerMePls** [comment]
thanks monkbroc, the particle serial wifi was what i needed.

**Comment by NinjaneerMePls** [comment]
now the photon breathes cyan i guess because it conneted to wifi but how can i claim it? the computer i'm using doesnt have wifi but is connected to the wifi router via copper connection.

**Comment by NinjaneerMePls** [comment]
i figured it out: do a particle device identify to find out the id ##### and then do a particle device add ##### to claim it.

And...............im talking to myself again

**Comment by eosrei** [comment]
Entire setup process for non-WiFi non-App setup:
```bash
$ sudo npm install -g particle-cli # sudo required on linux
# Plug in device, wait for flashing blue.
$ particle identify # Note device id
Your device id is 123456789
Your system firmware version is X.X.X
$ particle setup wifi
? Should I scan for nearby Wi-Fi networks? No
? SSID XXXXXXXXXX
? Security Type WPA2
? Wi-Fi Password hunter2
Done! Your device should now restart.
# Device flashes green, then breaths cyan.
$ particle cloud login
? Please enter your email address XXXXXXXX@XXXXXX.com
? Please enter your password *******************
> Successfully completed login!
$ particle device add 123456789
Claiming device 123456789
Successfully claimed device 123456789
```

**Comment by sandipsubedi** [comment]
I was also hanging there and "particle serial wifi" resolved the issue !

**Comment by danielmapar** [comment]
particle setup still broke in this case

**Comment by danielmapar** [comment]
https://github.com/spark/softap-setup-js/issues/23

**Comment by m-mcgowan** [comment]
Fixed by updating `softap-setup` to the latest version.
