### ISSUE TITLE
nyan command failed for `all`

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#124]
Ok i tested this briefly and `particle nyan deviceID on/off` works fine. `all` does not work with the introduction of interactive prompt for listDevices. Should not be too tough a fix.

**Comment by brycekahle** [comment]
Can you try `particle nyan on`?

**Comment by kennethlimcp** [comment]
hmmm.. interesting.. they actually work. The shell made it look at though it didn't. Somewhere in the code it is not exiting correctly.

**Comment by brycekahle** [comment]
So is this still an issue?

**Comment by kennethlimcp** [comment]
Guess not!
