### ISSUE TITLE
particle flash --usb says "Error writing firmware...no known App found." when file doesn't exist

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#128]
can we give a more helpful explanation as to what's happening, maybe show trying known apps vs. files?

**Comment by kennethlimcp** [comment]
@dmiddlecamp it is supposed to check if the keyword matches a known app or mention file doesn't exist. Is that not the behavior now?

**Comment by brycekahle** [comment]
@dmiddlecamp Can you post your full command?

**Comment by brycekahle** [comment]
https://github.com/spark/particle-cli/commit/984e75044a3732e6d5620f6624b9e47b02151b62 improved the error message
