### ISSUE TITLE
Particle setup not working for Cores

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#13]
simply plug in a core in Listening mode and type `particle setup`.

You can check that the core is indeed connected with `particle serial list`

@emilyrose, might want to fix this real quick or people with unclaimed cores will go through a lot of hassle just to claim it.Particle setup not working for Cores #195

**Comment by joegoggins** [comment]
+1 , really hoping for a fix for this sooner rather than later.

**Comment by brycekahle** [comment]
This should be fixed in 1.5.11
