### ISSUE TITLE
Particle setup function does not complete successfully

### ISSUE THREAD

**Issue by amicoleo** [spark/particle-cli#130]
Just a minor issue. But when setting up Photons with the command line, the sequence does not seem to complete successfully. I have the following line printed

    ! It doesn't look like your Photon has made it to the cloud yet.

Although if I unplug/plug back again the Photon, it connects fine (breathing cyan). 
I'm on OSX. I did update the firmware to 0.4.5

**Comment by emilyrose** [comment]
Ack! this might be an issue with the firmware. Maybe we should add a prompt to manually reset the Photon if it doesn't start trying to connect within a few seconds.

**Comment by brycekahle** [comment]
This was an API issue that has since been resolved.
