### ISSUE TITLE
Serial does not work on El Capitan

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#131]
Using`Version 10.11 OSx El Capitan`

The output from serial is: 

```  
{ comName: '/dev/cu.usbmodem1411',
    manufacturer: '',
    serialNumber: '',
    pnpId: '',
    locationId: '',
    vendorId: '',
    productId: '' } ]
```

I wonder if this is a `node-serialport` issue

**Comment by emilyrose** [comment]
Oh, joy!

**Comment by kennethlimcp** [comment]
@emilyrose what does it say on yours? 

I added `console.log(ports);` to 
https://github.com/spark/particle-cli/blob/master/commands/SerialCommand.js#L82

**Comment by kennethlimcp** [comment]
Just to document all the information i can find:

Product ID is weird..should be `0xd006`
```
Photon with WiFi:

  Product ID:	0xc006
  Vendor ID:	0x2b04
  Version:	2.00
  Serial Number:	00000000050C
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Particle
  Location ID:	0x14100000 / 4
  Current Available (mA):	1000
  Current Required (mA):	100
  Extra Operating Current (mA):	0
```

**Comment by brycekahle** [comment]
`d006` is for DFU mode. `c006` is for serial.

**Comment by dcohen613** [comment]
Is there a fix planned for this? It makes it kind of unusable for setting up via serial.

**Comment by brycekahle** [comment]
@dcohen613 Are you on the release version of El Capitan? My guess is this is a `node-serialport` issue, and if we get back blank information like posted above, it makes a fix very difficult.

**Comment by brycekahle** [comment]
I found voodootikigod/node-serialport#552

**Comment by emilyrose** [comment]
Would someone mind testing this with v1.8.9 of the CLI? Thanks! :smile_cat:

**Comment by kennethlimcp** [comment]
Tested NOT working on my side

**Comment by kennethlimcp** [comment]
Managed to get it working with a local compile using info from: https://github.com/voodootikigod/node-serialport/pull/607#issuecomment-147554578

**Comment by kennethlimcp** [comment]
@emilyrose it's working now after reinstalling v.1.8.11 which pulls in `node-serialport` for `v.2.0.1`

**Comment by emilyrose** [comment]
@kennethlimcp this is what I was hoping would happen, since we're not pinning serialport to a specific version. Thank for confirming & closing!

**Comment by kennethlimcp** [comment]
@emilyrose might want to bump 2.0.1 as minimal though..
