### ISSUE TITLE
particle publish doesn't show up as being from `MY_DEVICES`

### ISSUE THREAD

**Issue by jenesaisdiq** [spark/particle-cli#132]
Publishing from the CLI doesn't register on devices of mine that are subscribed to `MY_DEVICES`. It'd be very helpful to test commands and do control schemes without making the devices subscribed to public events, and all the abuse that exposes them to. My particular use case is sending calibration data to a microfleet of LED torches, and I've also written in functionality to add new WiFi networks to them via publishes... not so good when it's public.

**Comment by kennethlimcp** [comment]
@jenesaisdiq , Dave made this simple API and isn't something really built to support more (i think). What do you think if the publish statement from `particle publish` is listed as one of your device? 

Let's ping @dmiddlecamp if the API endpoint allows that or a change to the :cloud:  is required

**Comment by dmiddlecamp** [comment]
the CLI command is simplistic, but the API endpoint supports a param 'private'. If that's set to true, the event should register under private event subscriptions in your firmware.  :)

**Comment by kennethlimcp** [comment]
I can fix that! :D

**Comment by kennethlimcp** [comment]
@jenesaisdiq just so you know it's coming (finally) :)
