### ISSUE TITLE
Photon hasn't made it to the cloud yet.

### ISSUE THREAD

**Issue by ilanvolow** [spark/particle-cli#134]
I just received my photon yesterday and I tried to set it up using the iOS app, which did not work, and then I tried using the USB connection with OS X 10.10.5 and particle-cli. I got past the part where I "won the Internet" (yay) but then I got the message "It doesn't look like your Photon has made it to the cloud yet.". I entered my wifi info and pass several times to rule out a typo, if that helps.

**Comment by emilyrose** [comment]
Hey @ilanvolow,

I'm sorry you're having trouble! Would you mind pasting some output from the CLI attempting to setup your Photon? Alternatively, you can place the Photon into setup mode, and call `particle identify` from the command line. This should output your device ID, which you can then associate with your account on https://build.particle.io/build if the Photon is indeed connecting to the cloud (breathing cyan).

Thanks!

**Comment by ilanvolow** [comment]
Here's the output



> Obtaining device information...

> Requesting public key from the device...

> Setting the magical cloud claim code...

> Telling the Photon to apply your Wi-Fi configuration...

> The Photon will now attempt to connect to your Wi-Fi network...


> *Configuration complete! You've just won the internet!*

? *Would you like to return this computer to the wireless network you just
configured?* Yes*nfigured?* (Y/n) y

! It doesn't look like your Photon has made it to the cloud yet.


? *What would you like to do?* Check again to see if the Photon has
connected

! It doesn't look like your Photon has made it to the cloud yet.


? *What would you like to do?* (Use arrow keys)

❯ Reconfigure the Wi-Fi settings of the Photon

  Check again to see if the Photon has connected

The LED is still blinking blue.

**Comment by emilyrose** [comment]
If the LED is still blinking blue, that means that it was unable to make a successful connection to the Wi-Fi network you configured. Perhaps try using `particle serial wifi` to see if that has a different result?

**Comment by ilanvolow** [comment]
I tried it and the LED changed from blinking blue to blinking green and
then blinking cyan. I then go the message "! Something went wrong: Serial
timed out".

**Comment by kennethlimcp** [comment]
@ilanvolow,

- What does `particle --version` say?
- Have you tried performing a `particle update` in DFU mode?
- Does it blink cyan and have an occasional orange light?

**Comment by ilanvolow** [comment]
- 1.8.3

- The firmware upgrade went okay, though I'm still at 1.8.3 (latest
version?)

- particle serial wifi said the changes were accepted.

- I am seeing the flashing cyan with occasional orange light. I saw that
before and after I ran the upgrade.

**Comment by kennethlimcp** [comment]
Ok cool. 

- Is the Photon claimed already?
- Place the Photon in Listening mode and run `particle serial identify` to get the deviceID
- `particle keys new junk`
- `particle keys send deviceID junk.pub.pem` <---be sure to replace with actual deviceID
- reset the Photon and see if it enters breathing cyan

**Comment by ilanvolow** [comment]
I don't know if it's claimed. I wouldn't think so.

Performing those procedures didn't seem to have any effect.

**Comment by kitusmark** [comment]
Hi!
I have just the same problem with my photon. Tried everything I know...
Through the iOS app I fail at claiming my particle device.

``
Marcs-Macbook-Pro:~ Marc$ particle --version
1.8.16
``

I hold the setup button for more than 10 seconds to reset the wifi config ann then try to setup wifi via CLI.
Then I get **! Something went wrong: Serial port closed early** and the photon starts flashing cyan forever. Sometimes I get it to flash red sometimes meaning some handshaking but nothing more...

I'm quite desperate. Thanks :+1:

**Comment by brycekahle** [comment]
@kitusmark You should contact our support at hello@particle.io

**Comment by ilanvolow** [comment]
I ended up having the photon replaced through support.

**Comment by kitusmark** [comment]
Thanks, I'll do that.
