### ISSUE TITLE
Need functionality to pull device's mac address

### ISSUE THREAD

**Issue by harrisonhjones** [spark/particle-cli#140]
I would suggest something like `particle mac` to grab the mac address of a device connected via USB. Could also be returned when doing a `particle identify`

**Comment by brycekahle** [comment]
Try `particle serial mac`



—
Bryce KahleSenior Software Engineer

https://particle.io/

**Comment by harrisonhjones** [comment]
Thanks bryce. Anyone that wants please close this

**Comment by dougmartin17** [comment]
`particle serial mac` doesn't work for me. I get an error:
! serial: Error: Unable to find mac address in response

**Comment by brycekahle** [comment]
@dougmartin17 What device and firmware version are you running?

**Comment by dougmartin17** [comment]
Sorry, I think it's just due to me not being in listening mode.
