### ISSUE TITLE
Inconsistencies in CLI (and webhooks, Particle Dev, etc.) 

### ISSUE THREAD

**Issue by smm-bwf** [spark/particle-cli#143]
For background, please see this original post: https://community.particle.io/t/status-inconsistencies-between-cli-particle-dev-ide-webhooks/15043

In the screenshot below, you can see that devices are reporting as offline in "particle list" but functions from those same devices can be called, moments later, with accurate results coming back;  so the devices are definitely online, and report as such on the LED (breathing cyan). 

<img width="643" alt="screen shot 2015-09-28 at 4 50 59 pm" src="https://cloud.githubusercontent.com/assets/13375250/10175762/8a084058-66a5-11e5-955f-c889b1cf0682.png">

**Comment by emilyrose** [comment]
@smm-bwf,

Hey! Thanks for the alert! This is a known issue in the API that is scheduled to be fixed soon!

**Comment by smm-bwf** [comment]
OK - thanks.  Please let me know if it's updated.

On Tue, Sep 29, 2015 at 12:35 PM Emily Rose <notifications@github.com>
wrote:

> @smm-bwf <https://github.com/smm-bwf>,
>
> Hey! Thanks for the alert! This is a known issue in the API that is
> scheduled to be fixed soon!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/particle-cli/issues/143#issuecomment-144165934>.
>
-- 

--
Sean McDonald

President, Bitwater Farms

sean@bitwaterfarms.com | 828.545.9539

**Comment by emilyrose** [comment]
@smm-bwf I will close this issue when I've confirmed that the API is no longer exhibiting this bug. Thanks again! :smile_cat:

**Comment by brycekahle** [comment]
This issue has been fixed in the API.
