### ISSUE TITLE
serial timeout during setup wifi

### ISSUE THREAD

**Issue by m-mcgowan** [spark/particle-cli#144]
With a core running 0.4.6 firmware in listening mode connected via USB

```
mbp:main mat1$ particle --version
1.8.4

? Should I scan for nearby Wi-Fi networks? Yes
? Select the Wi-Fi network with which you wish to connect your device: Altibox586485
? Should I try to auto-detect the wireless security type? Yes
! Something went wrong: Serial timed out
```

Same result if I choose "No" for auto-detecting the wireless security type. 

When I connect to serial, the serial monitor shows  "Password: "

**Comment by sasilverain** [comment]
I got the same issue.  I tried resetting the core to factory defaults (details here -https://community.particle.io/t/spark-core-troubleshooting-guide-spark-team/696) and tried connecting through Terminal again and all worked.

Hope this helps...
