### ISSUE TITLE
Compile doesn't allow specifying platform ID

### ISSUE THREAD

**Issue by suda** [spark/particle-cli#15]
`compile` command should take an optional [`deviceID`, `platformID` and `productID`](https://github.com/spark/sparkjs/blob/master/lib/spark-api.js#L382) parameters and pass them to the API.

**Comment by m-mcgowan** [comment]
We can also infer the connected device from the USB VID/PID.

**Comment by pkourany** [comment]
@m-mcgowan, what if the device is not connected?  Having an explicit command is important IMO.

**Comment by kennethlimcp** [comment]
There are many ways to go do this:

- `particle compile --photon xxxxx`
- `particle compile --core xxx`
- detect USB VID/PID and compile accordingly
- Use the :cloud: setting where it already knows which device is which.
   - eg. `particle compile my_photon xxx` or `particle compile oh_yeah_white_core xxx`

**Comment by pkourany** [comment]
Ken, I agree with everything you said!

**Comment by m-mcgowan** [comment]
and that `particle compile xxx` should fail if it can't autodetect from the connected device, since no other means of knowing the target was given.

**Comment by kennethlimcp** [comment]
Thinking of a `particle compile device_type xxxxx` for now without USB detection. Thoughts?

detection is cool but still requires a `Y/n` response in case the user wants to compile for other platform and that will quickly become a tedious `hit enter` or `no` chore. We can always add that later :)

**Comment by pkourany** [comment]
From my own experience, I often just want to test compile and not flash so not having a connected device is common IMO. When a target is specified for flashing, that's when it should fail when type and actual target don't match.

**Comment by kennethlimcp** [comment]
currently, `compile` and `flash` are 2 separate commands and there's no coupling for what you mentioned: "When a target is specified for flashing, that's when it should fail when type and actual target don't match."

If you do a OTA Flash, the device name/id you use will tell the :cloud: which platform to compile for.

If you do a compile which returns a `.bin`, we need to specify which platform like:

`particle compile core xxx`

**Comment by pkourany** [comment]
Ken, I thought you could compile and flash in one command (I never used it
so it was a guess on my part!).  Glad you clarified!  In regards to the
other stuff, you agree completely.



Paul Kourany, P.Eng., PMP, ITIL
IT Worx Services
President

**Comment by dmiddlecamp** [comment]
you can compile and flash in one command, "compile" and "flash" take the same general arguments, just one has a target device

**Comment by kennethlimcp** [comment]
@emilyrose, can be closed with https://github.com/spark/particle-cli/commit/659fc2ca9594f17add5b83f93be6105b80a12186

**Comment by emilyrose** [comment]
thanks, @kennethlimcp!
