### ISSUE TITLE
False error: "Function call failed Function <functionName> not found"

### ISSUE THREAD

**Issue by pomplesiegel** [spark/particle-cli#156]
Just had an experience wherein a Photon which was successfully online, running system FW 0.4.5 and responding to `particle get` calls. However, CLI did not allow me to make a function call to this Photon, stating

````sh
Function call failed  Function <ourFunctionName> not found
````

After restarting the Photon, the function call worked fine, running successfully and returning a `1`.

However, this was in a customer's home, so asking them to restart the tower (now strangely out of reach via function calls) is certainly not ideal. 

Is CLI restricting our function calls to Photons based on what functions have been verified registered w/ the cloud? From a deployment perspective, i would rather have a timeout when calling a function that doesn't exist, rather than a blocking error when calling a function which **does** exist.

**Comment by m-mcgowan** [comment]
When you say the photon was online, can you detail how you knew that?

**Comment by pomplesiegel** [comment]
Sure! I know it was online, happily running our user app, as it repeatedly responded to our app-specific `get` calls OTA using CLI (version 1.8.8).

**Comment by brycekahle** [comment]
@pomplesiegel The cloud is the one restricting calls to functions registered with the cloud. A lot of cloud functionality depends on that information being accurate, plus it also prevents unnecessary data transfer. 

It sounds like somehow the cloud did not have up to date information, which is a different issue.

**Comment by brycekahle** [comment]
Closing as not a CLI issue.
