### ISSUE TITLE
Printout system firmware version before particle update

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#157]
It would be good for `particle update` to mention the current version of system firmware that is flashed to the device in case people are wondering. 

We can also keep the older binaries should people want to perform rollback like how they can in the Web IDE

**Comment by toSvenson** [comment]
A quick lookup using `particle device version` would be useful too.

**Comment by brycekahle** [comment]
@toSvenson that is covered by #95

**Comment by brycekahle** [comment]
@kennethlimcp `particle update` requires the device in DFU mode, whereas retrieving the system firmware version via the `v` command requires listening mode.

**Comment by brycekahle** [comment]
I think this would be difficult and really confusing because we would need to instruct the user to go to listening mode *and then* DFU mode.
