### ISSUE TITLE
Parse binaries before DFU flash, and warn if they don't make sense to flash to that address

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#159]
I used ```particle flash --usb something.bin``` to try and update a system-part, and I wound up in a difficult to diagnose safe mode that can't be healed automatically.  In this scenario the CLI let me replace the user app with something that can't run at that address, etc.

If we use the binary-version-reader, we can at least tell if the function of the app is a user app, or a system part or whatnot, and either throw it at the correct address, or warn that it's going to the wrong spot, etc.

**Comment by brycekahle** [comment]
See #32

**Comment by dmiddlecamp** [comment]
Totes, would integrate nicely with that feature / we could suggest they use that flag.  I'd love a warning that I'm about to do something silly though :)

**Comment by brycekahle** [comment]
I was talking about what Mat suggested in his comment, where it automagically figures out the address it should flash to https://github.com/spark/particle-cli/issues/32#issuecomment-134039067
