### ISSUE TITLE
Default compiled firmware filename should indicate the platform

### ISSUE THREAD

**Issue by suda** [spark/particle-cli#16]
Depending on [device's platformID](https://github.com/spark/spark-dev/blob/master/lib/spark-dev.coffee#L361) filename of created file should reflect it similarly as [Particle Dev does it](https://github.com/spark/spark-dev/blob/master/lib/spark-dev.coffee#L524).

**Comment by kennethlimcp** [comment]
@suda i'm guess thing will have to make use of https://github.com/spark/particle-cli/issues/15 fix first to know which device the user wants to compile against?

I can get a PR for issue 15 since it's probably not too much work :)

**Comment by kennethlimcp** [comment]
@emilyrose, can be closed with https://github.com/spark/particle-cli/commit/659fc2ca9594f17add5b83f93be6105b80a12186
