### ISSUE TITLE
keys doctor changing product_id of device?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#162]
"After Keys Doctor, P1 is shown as a Core on Dev and Other on WebIDE"

https://community.particle.io/t/after-keys-doctor-p1-is-shown-as-a-core-on-dev-and-other-on-webide/16847

**Comment by brycekahle** [comment]
I've checked and `keys doctor` on its own could not do this. I suspect there is a bug somewhere else.
