### ISSUE TITLE
Do not allow customers to claim a device as a user

### ISSUE THREAD

**Issue by jme783** [spark/particle-cli#166]
Currently, you are allowed to go through the user-claiming process regardless of if you are logged into the CLI as a `user` or a `customer`. This results in devices being claimed by `customers`, and saving erroneous attributes to the `core` document.

For instance, logging into the CLI as a customer `jeff@particle.io`, and running `particle setup`, will walk me through the claiming process and save a `user_id` on the device that is actually a `customer_id` (the ID does not correspond to a user at all!).

If a customer is logged in, they should not be allowed to run `particle setup`. They should receive a message like: 

`You must be logged in as a user to run this command. Type particle logout, and log back in as a user to re-run this command`

**Comment by brycekahle** [comment]
This will be addressed at the API level instead of handling it in the CLI.

**Comment by dmiddlecamp** [comment]
Weren't we going to detect and warn or something?

**Comment by brycekahle** [comment]
I think it is best to handle this at the API level, either by fixing the bug or returning a proper error which can be propagated to the CLI. Having the CLI know whether an access token belongs to a user/customer is a lot of extra work.
