### ISSUE TITLE
DFU flash fails silently on Linux

### ISSUE THREAD

**Issue by monkbroc** [spark/particle-cli#171]
Using master (commit 0aec49a1), I can't flash with DFU on Linux. It fails silently so I assume a promise is falling through the cracks. The released 1.8.16 works fine.

```
monkbroc@slim:~/Programming/particle-cli$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
monkbroc@slim:~/Programming/particle-cli$ bin/particle.js flash --usb tinker
monkbroc@slim:~/Programming/particle-cli$ git checkout v1.8.16
Switched to branch 'v1.8.16'
monkbroc@slim:~/Programming/particle-cli$ bin/particle.js flash --usb tinker
dfu-util: Cannot open DFU device 2b04:d006


Error writing firmware...dfu-util: Cannot open DFU device 2b04:d006


monkbroc@slim:~/Programming/particle-cli$ 
```

**Comment by brycekahle** [comment]
Thanks for the report. I will take a look.

**Comment by monkbroc** [comment]
I was looking at updating #82 but I'll wait a bit since the baseline isn't working.

**Comment by brycekahle** [comment]
I do find it odd that you didn't even get the `console` output.

**Comment by brycekahle** [comment]
Give https://github.com/spark/particle-cli/commit/f1b38f9b2c36dffe2861ce27f822a0bd5f0ce133 a shot

**Comment by monkbroc** [comment]
Thanks @brycekahle. That fixes it!

**Comment by brycekahle** [comment]
No problem. This just exposed something that I will need to check other commands for.
