### ISSUE TITLE
Duo no longer appears in device serial list

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#173]

**Comment by brycekahle** [comment]
More details please? Output from `node-serialport` would be helpful too. Stick a `console.log(ports);` at https://github.com/spark/particle-cli/blob/master/commands/SerialCommand.js#L80

**Comment by dmiddlecamp** [comment]
HI @brycekahle,

  Sorry, this was more a reminder for myself than a bug report for you, no need to jump on this asap.  :) 

Thanks,
David
