### ISSUE TITLE
`particle call` should have a non-zero exit status when the call fails

### ISSUE THREAD

**Issue by jtzemp** [spark/particle-cli#182]
In testing the Electron with Tinker on it, I did:

    $ particle call $DEVICE_NAME digitalwrite "D7,HIGH"

And I got back:

    Function call failed  Something went wrong calling this function: GET coap://127.0.0.1/t (T=CON ID=14 TK=02)

And `echo $?` returned '0'.

Just for context, I was talking over UDP, and everything was working fine until a service deploy. I know that has nothing to do with the CLI, just mentioning it here in case there _is_ a code path that returns a non-zero exit code for failures most of the time, but this time didn't.

**Comment by brycekahle** [comment]
Is this with the latest version? There has been a lot of work around this lately.

**Comment by jtzemp** [comment]
Yeah, the latest released version.
