### ISSUE TITLE
Select version for Compile

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#183]
Right now we are able to target a particular device for compile but should also be able to target a specific version.

My idea is to have a `.json` file for the CLI to parse:

```json
{
 "device": "photon",
 "version": "0.4.7",
 "directory": "."
}
```

**Comment by KeighDub** [comment]
Agree 100%. Would love a way to lock the version we're building against.

**Comment by brycekahle** [comment]
I think a general solution would be the ability to specify a JSON file to set command line arguments for any command.

**Comment by kennethlimcp** [comment]
Depends on how much dev time you guys have to make that happen? If i know what the `form.append()` is for targeting version i can put together a PR for now so that people can actually use it instead of waiting for the general solution

**Comment by brycekahle** [comment]
I'm not sure there is a direct way to translate a version `0.4.7` into a build target at the moment. @suda would know for sure.

**Comment by suda** [comment]
There is build targets endpoint used by Build to show/specify versions. It could be used by CLI too.

**Comment by kennethlimcp** [comment]
@suda can you provide the necessary endpoint info?

**Comment by brycekahle** [comment]
@suda ping

**Comment by suda** [comment]
Oh sorry for not responding. The API endpoint isn't documented publicly yet but you can find it here: https://api.particle.io/v1/build_targets?featured=true&access_token=<TOKEN>
