### ISSUE TITLE
auto multi-get variable is broken

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#187]

**Comment by brycekahle** [comment]
Do you have an example of the command you were running?

**Comment by dmiddlecamp** [comment]
particle get temp

where temp is a variable on multiple devices

**Comment by brycekahle** [comment]
Is that a valid syntax? I thought it was `particle get all temp`?

**Comment by dmiddlecamp** [comment]
I think it was valid syntax at one point (?), but I doubt it's heavily used / I could be wrong. Nice to have something that supports this behavior, I'm open to the syntax you posted totally.  :)
