### ISSUE TITLE
particle publish doesn't detect invalid token

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#193]

**Comment by brycekahle** [comment]
Hmm, it definitely has code to do so at https://github.com/spark/particle-cli/blob/master/lib/ApiClient.js#L646

**Comment by dmiddlecamp** [comment]
weird, maybe it's an API issue then, not returning an error code or something.  For whatever reason I wasn't seeing it when my token was bad

**Comment by brycekahle** [comment]
I'll do some more testing to verify behavior.

**Comment by brycekahle** [comment]
Tested and it works.

**Comment by dmiddlecamp** [comment]
thanks for checking!
