### ISSUE TITLE
Old link to SPARK_CLI referenced on OPEN SOURCE page linked in Discourse 

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#194]
I had pointed this out quite a while ago, but can't find the issue anymore, but the <kbd>OPEN SOURCE</kbd> link top right on https://community.particle.io links to a [GitHub page](http://spark.github.io/) which still has several links to ***old*** repos linked.

So e.g. when I want to open a PARTICLE_CLI issue I can only find the SPARK_CLI box with the <kbd>Issues</kbd> issues button which leads me to 
 https://github.com/spark/spark-cli/issues
instead of 
 https://github.com/spark/particle-cli/issues

Either these two issue trackers (and possibly the respective repos) should be updated and/or pulled together into one.
And the links should reference the most recent repos.

**Comment by brycekahle** [comment]
Thanks for the heads up. I've gone ahead and updated that site. In the future, you can open issues on that site at https://github.com/spark/spark.github.io/issues
