### ISSUE TITLE
Spark Core: Error writing firmware...CRC is invalid, use --force to override

### ISSUE THREAD

**Issue by emartinez167** [spark/particle-cli#196]
I re-installed particle-cli on a Mac (trying to get my old Spark Cores to work) and now I get this error when trying to update the firmware:

>particle flash --usb cc3000
running dfu-util -l
Found DFU device 1d50:607f

Error writing firmware...CRC is invalid, use --force to override

**Comment by brycekahle** [comment]
Add `--force` to your command to bypass this error. I will fix the CLI to not warn about known apps in the future.

**Comment by emartinez167** [comment]
I did, just wanted to make sure it would be ok. Thanks. This can be closed.

Regards,

Ernesto
