### ISSUE TITLE
npm update not working

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#2]
using `sudo npm update -g particle-cli`, there's an error: 

```
npm ERR! Refusing to delete: /usr/local/bin/spark not in /usr/local/lib/node_modules/particle-cli
File exists: /usr/local/bin/spark
Move it away, and try again. 

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "update" "-g" "particle-cli" "--verbose"
npm ERR! cwd /Users/kennethlimcp
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/local/bin/spark
npm ERR! code EEXIST
npm verb exit [ 1, true ]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kennethlimcp/npm-debug.log
npm ERR! not ok code 0
```

Seems like an issue if you have `spark-cli` already installed

**Comment by emilyrose** [comment]
ah, good catch! I will add a prominent note to the docs that a user should uninstall `spark-cli` first.

**Comment by kennethlimcp** [comment]
It should also be in the docs but i don't have access to fix it.

**Comment by brycekahle** [comment]
I agree that we don't need to include `spark` binary. The user has to explicitly install particle-cli, so I don't think we need to maintain that binary. We could add a `postinstall` script to detect if `spark-cli` is installed and warn the user to uninstall it with an example command.

**Comment by emilyrose** [comment]
@kennethlimcp the reason is that many of our customers are already quite used to using the `spark` command, and it's not super user-friendly to just yank a command for which people have built up "muscle memory". Making both available, but with a gentle reminder when you use `spark` seemed like the best option; but I'm willing to discuss, it I suppose.

There is no `spark` binary per se. I've just listed both the `spark` and `particle` commands as binaries in the CLI's package.json, which both actually run `bin/particle.js`. 

I don't agree that it should simply be removed, but we can chat it out...

**Comment by brycekahle** [comment]
While I agree in principle, the inability to install particle-cli while having spark-cli installed is a major downside. Also the longer we allow the usage of `spark` the longer it will take to transition everyone to using `particle`.

**Comment by joegoggins** [comment]
I agree with @brycekahle , forcing everyone through an upgrade user experience that begins with an error is no good. If users don't have time to change their scripts or day to day usage pattern from `spark` to `particle`, they can stay on `spark-cli`. Enabling usage of `spark` even when using the latest `particle-cli` is confusing.

**Comment by zsup** [comment]
Whatever the solution we put in place, `npm install -g particle-cli` and `npm update -g particle-cli` should not error out if at all possible. Regardless of how well documented it is, many people will attempt to install without looking at the docs at all.

**Comment by emilyrose** [comment]
so for now I've just removed the `spark` "binary" from the package.json.
