### ISSUE TITLE
Backspace erases earlier console output

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#20]
Using `particle serial wifi`, hitting the backspace results in the prompt moving up one line and further, "erasing" the previous console output

**Comment by brycekahle** [comment]
Which part of the process was this? I cannot reproduce it.

**Comment by brycekahle** [comment]
Details about your environment would help too. OS, shell, etc.

**Comment by kennethlimcp** [comment]
Try `particle serial wifi` and hit backspace

**Comment by brycekahle** [comment]
Yeah, it doesn't happen for me. What shell are you using?

**Comment by kennethlimcp** [comment]
just normal mac terminal

**Comment by brycekahle** [comment]
Does it still happen with `1.7.0`?

**Comment by kennethlimcp** [comment]
Seeing is believing - https://dl.dropboxusercontent.com/u/36134145/CLI-backspace-issue.mov

**Comment by brycekahle** [comment]
Thanks. That helps a lot actually.

**Comment by kennethlimcp** [comment]
Update to `v1.7.01 but not surprisingly it behaved the same
