### ISSUE TITLE
Document the `--target` switch for firmware versions

### ISSUE THREAD

**Issue by technobly** [spark/particle-cli#204]
Compiling with target works
```
particle flash <deviceid> myapp.ino --target 0.4.8
```

Compiled binaries don't seem to work, but would be nice if they did :)
```
particle update --target 0.4.7
particle flash <deviceid> tinker --target 0.4.7
```

**Comment by brycekahle** [comment]
I'm not sure what you mean by compiled binaries?

**Comment by technobly** [comment]
xxx.bin System part 1 & 2 and tinker for various platforms :)  They only send the latest, but it would be nice if older versions could be pulled from github releases and could use `--target` as well.
