### ISSUE TITLE
`particle update` does not throw error if `dfu-util` errors

### ISSUE THREAD

**Issue by technobly** [spark/particle-cli#206]
Bootloader firmware will [**now**](https://github.com/spark/firmware/commit/35e8aef998966ae0c2bd6e387543bc8c58f94eed) propagate an error back to the host now when there is a write/erase failure during DFU transfer, however the CLI does not indicate an error if it sees one during `particle update`

Note: This may be an inherent issue with all `dfu-util` usage in the CLI.

[**This special electron v0.4.8-rc.6/v0.4.9 compatible bootloader**](https://dl.dropboxusercontent.com/u/41117656/firmware/bootloader-dfu-write-verify-retry-then-error-after-15s.bin) will cause a write error after 15 seconds of uptime, you can use this to verify the issue and fix.  Put in DFU mode, and wait about 10 seconds, then start the `particle update`.  If using `dfu-util` directly you can see the progress bar stop and error reported.

**Comment by brycekahle** [comment]
Do you know what error `dfu-util` reports?

**Comment by brycekahle** [comment]
A full output from `dfu-util` would be helpful.

**Comment by technobly** [comment]
Here's a sample output:
```
dfu10part1 ~/Downloads/binaries/system-part1-v0.4.8-rc.6-electron.bin 
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 2b04:d00a
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 4096
DfuSe interface name: "Internal Flash   "
Downloading to address = 0x08020000, size = 130884
Download	[==============           ]  56%        73728 bytesdfu-util: Error during download get_status
```

The error message during erase is different though.

**Comment by technobly** [comment]
[**Here's a bootloader**](https://dl.dropboxusercontent.com/u/41117656/firmware/bootloader-dfu-write-verify-retry-then-erase-error-after-15s.bin) that will cause an Erase error after 15 seconds of up time, so easy to make a transfer pass, then fail.

Here's a sample output of the Erase error:
```
dfu10part1 ~/Downloads/binaries/system-part1-v0.4.8-rc.6-electron.bin 
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 2b04:d00a
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 4096
DfuSe interface name: "Internal Flash   "
Downloading to address = 0x08020000, size = 130884
Download	[                         ]   0%            0 bytesdfu-util: Error during special command "ERASE_PAGE" get_status
```

**Comment by brycekahle** [comment]
Ok. I know the issue. It is currently ignoring `stderr` output with `get_status` as an error because `Error during download get_status` was a non-error before.

**Comment by technobly** [comment]
Cool.. I know there are still some weird cases, but here's what things look like for me in this one case when everything completes correctly.

```
dfu10part1 ~/Downloads/binaries/system-part1-v0.4.8-rc.6-electron.bin 
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 2b04:d00a
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 4096
DfuSe interface name: "Internal Flash   "
Downloading to address = 0x08020000, size = 130884
Download	[=========================] 100%       130884 bytes
Download done.
File downloaded successfully
```

```
dfu-util --version
dfu-util 0.8
```

**Comment by technobly** [comment]
@brycekahle I think we should also add this error as well `Error during special command "ERASE_PAGE" get_status` which could happen if the write protection cannot be changed, or noise/voltage issues are present.

**Comment by brycekahle** [comment]
We should ignore that error?

**Comment by technobly** [comment]
Nope, if we see the Erase error we can be reasonably sure that the dfu-util process failed to write the image correctly.  We should *not* say everything completely successfully in that case.

**Comment by brycekahle** [comment]
Great, so the change I made only ignores a very specific message. Everything else is treated like an error.

**Comment by technobly** [comment]
Ahh.. Hmm..  When I looked at your change, it included a test for `Error during download get_status` which is the Write error specifically.  So you are saying you are ignoring this specific error?

**Comment by technobly** [comment]
I just checked with the updated CLI and it still ignores the Write error, which you can reproduce with the binary in the first post.  Second post of mine has the error.

**Comment by brycekahle** [comment]
Hmm, ok. Re-opening.

**Comment by technobly** [comment]
It also continues to ignore the Erase error, albeit ending `particle update` early.  It says "System firmware update successfully completed!"
