### ISSUE TITLE
`particle claim` should work when supplying an ID with uppercase hex letters

### ISSUE THREAD

**Issue by opyh** [spark/particle-cli#208]
We just tried to claim a Photon by supplying its ID that we copy&pasted from the command line output of `particle-cli`. It worked neither with the Particle Build web interface nor with `particle-cli` ('Could not claim device')

The ID was `220034000E47343432313031`.

When we changed the letter `E` to `e`, it worked. Could it be that IDs are interpreted case sensitive somewhere on the server? In this case the tool should output the ID in lowercase or the server should convert the IDs to lowercase before trying to add them to your account.

**Comment by brycekahle** [comment]
What command did you run that output the ID in uppercase?

**Comment by opyh** [comment]
If I remember correctly, this was part of the `particle setup` output.

**Comment by brycekahle** [comment]
I've fixed the `setup` output to lowercase. I will file an internal bug against our API to be case-insensitive.

**Comment by opyh** [comment]
Thanks for your quick response!
