### ISSUE TITLE
Particle Login gives : ECONNREFUSED

### ISSUE THREAD

**Issue by mojtabacazi** [spark/particle-cli#21]
#: particle cloud login
? Please enter your email address: XXXXXXXX
? Please enter your password: ********
! There was an error logging you in! Let's try again.
! Login Failed: Error: connect ECONNREFUSED

Thoughts?

Running on MacBook 10.10

**Comment by kennethlimcp** [comment]
What does `particle config identify` say?

**Comment by mojtabacazi** [comment]
Current profile: particle
Using API: http://104.236.177.224:8080
Access token: *********

**Comment by mojtabacazi** [comment]
It was pointing to localhost, fixed and working now.
Thank you

**Comment by emilyrose** [comment]
@mojtabacazi thanks for the report! I will make that error output add some suggestions! Glad you got it fixed.

Thanks @kennethlimcp! :smile_cat:
