### ISSUE TITLE
Can we get the CLI working with the latest versions of node?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#219]

**Comment by brycekahle** [comment]
It does. What version did you try?

**Comment by dmiddlecamp** [comment]
Apologies!  I had heard reports that some hackathons / conferences were struggling with incompatibilities with particular versions of node (4, 5), but I don't have specifics yet

**Comment by dmiddlecamp** [comment]
Thanks for adding those versions of node to the testing suite!
