### ISSUE TITLE
Photon OTA using particle-cli

### ISSUE THREAD

**Issue by mojtabacazi** [spark/particle-cli#22]
Can Particle-cli be used for photon OTA? `--usb` does work for me but not the OTA. No error it just causes my photon to rest to factory firmware. 

Tried exact same code  on Cloud IDE and it works fine

**Comment by kennethlimcp** [comment]
@mojtabacazi,

There's a similar issue here: https://github.com/spark/particle-cli/issues/15

Basically we need to tell the build farm which device are we compiling for so improvements to the CLI needs to be made

**Comment by mojtabacazi** [comment]
well I've compiled using `make PLATFROM=photon ...` and when I do `particle flash \UUID\ blink.bin` photon start flashing magenta but then it rest to factory firmware not what I've compiled. 

`particle flash --usb` works fine

**Comment by kennethlimcp** [comment]
Ok i guess you are using the `develop` branch? Or are you using the `V0.4.0` stable release?

**Comment by mojtabacazi** [comment]
`particle --version`
1.5.11

**Comment by kennethlimcp** [comment]
I means for `make PLATFROM=photon ...` Where did you download the firmware source code?

**Comment by mojtabacazi** [comment]
oh that yea `develop` branch

**Comment by kennethlimcp** [comment]
Be sure to `git pull` the latest copy and upgrade the system firmware to test again - https://github.com/spark/firmware/blob/develop/docs/build.md#updating-system-firmware-photon

**Comment by mojtabacazi** [comment]
did that before. not working still.

**Comment by emilyrose** [comment]
hey @mojtabacazi! I'm working on this feature as we speak. 

As @kennethlimcp mentioned, the CLI isn't yet informing the API the platform for which to compile.

**Comment by mojtabacazi** [comment]
@emilyrose Got it but I don't get how it's related to compiling the code?

**Comment by kennethlimcp** [comment]
@mojtabacazi , you might want to open a thread at: https://community.particle.io/ as this is not a CLI-related issue

**Comment by kennethlimcp** [comment]
Similar to https://github.com/spark/particle-cli/issues/15, so :+1:  to close
