### ISSUE TITLE
Subscribe command shows ALL events (including devices I don't own)

### ISSUE THREAD

**Issue by punitganshani** [spark/particle-cli#222]
**Issue:**
- When we login to our Particle Dashboard, we can view events generated by our Particle Devices
- When we use NODE CLI, we can view events generated by ALL Particle Devices (including those we don't own)

**This is a potential security issue as I can view data from other devices that I don't have access to**

**Replication steps:**

- Use `nodejs` CLI and login using Particle subscription email and password
- Type command `particle subscribe ConnectTheDots`
- See the output- it has events from devices that don't belong to the logged in subscription

<img width="946" alt="spark" src="https://cloud.githubusercontent.com/assets/1032553/13430986/77557490-e002-11e5-9ce5-ddaab7e08c98.PNG">

- Terminate the above and try command `particle subscribe`
- See the output- it has ALL events from ALL devices. None of these events are from my device

<img width="910" alt="spark2" src="https://cloud.githubusercontent.com/assets/1032553/13431035/a78be144-e002-11e5-9682-6932c518caa9.PNG">

**Comment by kennethlimcp** [comment]
They are public events. If you set them to private, they will not appear in the public firehose.

So it's like people are making them public which is why you are see it.

See the `PRIVATE` example: https://docs.particle.io/reference/firmware/electron/#particle-publish-

**Comment by dmiddlecamp** [comment]
Thanks @kennethlimcp !

Thanks for reporting, but yes, this is the public event firehose!  We understand there is some confusion about public vs. private events, and we're trying to improve our documentation and examples and defaults to make this easier.

Thanks!
David

**Comment by punitganshani** [comment]
I believe by default all events should be private and only if required we should allow making them public. This will prevent accidental event publication.

My 2c
