### ISSUE TITLE
Claim Photon over USB

### ISSUE THREAD

**Issue by monkbroc** [spark/particle-cli#227]
When I write `particle setup` and I have a Photon connected to the USB port, it says `I have detected a Photon connected via USB. The Photon supports secure Wi-Fi setup. We'll try that first.`

When I answer No to `? Would you like to wait and monitor for Photons entering setup mode? (Y/n)` It should not say `> Ok, bye! Don't forget`particle help`if you're stuck! <3`

It should instead continue with the serial setup?

Assume I'm on a computer that doesn't have a wireless card.

**Comment by brycekahle** [comment]
So you cannot send a claim code via serial, which is a big part of the setup.

**Comment by monkbroc** [comment]
In that case I suggest changing the text to "I have detected a Photon connected via USB. We will set it up using a secure Wi-Fi connection".

**Comment by monkbroc** [comment]
With this firmware PR, it's possible to claim a Photon via USB serial.
https://github.com/spark/firmware/pull/960

**Comment by monkbroc** [comment]
This is done
