### ISSUE TITLE
Unhelpful error message in rename when device name doesn't exist

### ISSUE THREAD

**Issue by monkbroc** [spark/particle-cli#228]
```
particle device rename abc def
Renaming device abc
Failed to rename abc, server said undefined
```

Expected to see an error like "abc cannot be found"

**Comment by brycekahle** [comment]
I have a suspicion that when https://github.com/spark/cloud/issues/3 is fixed, this will be as well.

**Comment by monkbroc** [comment]
The error is actually different. Since the API return 403 permission denied for any device ID/name that it doesn't recognize the CLI should say "I can't find that device".

Here's the cloud API response:
```
{
  "error": "Permission Denied",
  "info": "I didn't recognize that device name or ID, try opening https://api.particle.io/v1/devices?access_token=1d0fbc38f5b1a7fa3ad67423934bae89a5f02de9"
}
```

**Comment by brycekahle** [comment]
Ah, yes subtle difference.
