### ISSUE TITLE
Some commands use new vs create, delete vs remove

### ISSUE THREAD

**Issue by monkbroc** [spark/particle-cli#229]
Standardize the CLI verbs for creating and removing across all commands.

Make sure to keep the old synonyms, but hide them in the help.

**Comment by m-mcgowan** [comment]
`
token new
keys new
webhook create
library create
project create
device add

device remove
webhook delete
`

I'm not sure that these remove/delete are fully synonymous. E.g.

`device delete` vs `device remove`

But they are close enough that people may forget exactly which one we chose to use in a given situation. So for now I will add the alternate version in all cases. 

Then it just remains to decide which one we display in the help.
