### ISSUE TITLE
Standardized command verb

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#23]
Proposing:

**Webhook**
- `add` (sounds a little funny, original is `create`)
- `remove`

this is in line with `particle device`
- `particle device add`
- `particle device remove`

**Comment by emilyrose** [comment]
I'm happy with add/remove, but would also love to support 'del' as well.

**Comment by kennethlimcp** [comment]
Sound like a one line addition: https://github.com/spark/particle-cli/blob/master/commands/WebhookCommands.js#L94
