### ISSUE TITLE
Display Flash/RAM Percentages like web IDE

### ISSUE THREAD

**Issue by wgbartley** [spark/particle-cli#230]
When code is compiled/flashed in the web IDE, it displays something along the lines of

```
Output of arm-none-eabi-size:

text    data    bss dec hex
77280   1312    11856   90448   16150

In a nutshell:
Flash used  78592 / 110592  71.1 %
RAM used    13168 / 20480   64.3 %
```

I think this would be very handy for the CLI as well.  I'm not sure if this might break expected behavior for some since I could see parsing the usual output as some sort of automated/scripted process.  Perhaps a `--percent` flag could be used to get the extra information.

For those with access, there was discussion about this in the web IDE for the Spark Core a long time ago -- https://community.particle.io/t/show-ram-usage-in-ide/4207

**Comment by m-mcgowan** [comment]
This is implemented in the latest version at  least:

```
Compiling code for photon

Including:
    GPS_HardwareSerial_Parsing.ino
    ../../library.properties
    ../../src/Adafruit_GPS.cpp
    ../../src/Adafruit_GPS.h
attempting to compile firmware 
downloading binary from: /v1/binaries/5888936c41af1650add20d4b
saving to: photon_firmware_1485345641505.bin
Memory use: 
   text	   data	    bss	    dec	    hex	filename
  21324	    172	   1808	  23304	   5b08	
Compile succeeded.
```
