### ISSUE TITLE
particle serial monitor "poll until serial port is available" feature

### ISSUE THREAD

**Issue by joegoggins** [spark/particle-cli#234]
I can capture serial logs using `particle serial monitor`, however, I miss the first part of the output because I need to time my execution of this command to be right after it opens the serial port, which is at least .5-1 seconds behind when the output starts, so I miss the first part.

Is there a good way to do this? Would adding a serial port poll flag like `--poll 1ms` to the `serial monitor` make sense??

The use case is something like this:

```
As a user debugging a complex Electron issue
I want to be able to capture the serial output logs from the very beginning and not miss the first second of serial output
```

**Comment by m-mcgowan** [comment]
Implemented in the PR above, shipped in 1.19.4. Thanks @derekmpeterson!
