### ISSUE TITLE
webhook delete

### ISSUE THREAD

**Issue by elevatorguy** [spark/particle-cli#243]
v1.12.0
This is apparent in the dashboard integrations version of webhooks. but verified list using CLI.
a webhook will be deleted, and no longer shows in "particle webhook list" but the webhook is still being called and shows in the dashboard logs.

**Comment by kennethlimcp** [comment]
`particle list` shows a list of devices and not webhooks. Are you referring to `particle webhook list`?

**Comment by elevatorguy** [comment]
sorry, i meant the latter.

**Comment by kennethlimcp** [comment]
Do you happen to have another webhook listening to the same eventName?

**Comment by elevatorguy** [comment]
I think that is what caused the issue. But don't anymore.

**Comment by Knoose** [comment]
I'm having the same issue with phantom/zombie webhooks. I had webhooks with the same name, but I've since deleted them all. Yet, they are still showing up and particle webhook list returns 0.

**Comment by dmiddlecamp** [comment]
Thanks for the report!

**Comment by stuboo** [comment]
I'm apparently having the same issue. This sounds like the only explanation. I used the CLI to set up my webhooks. If I have time later today, I'm gonna change my webhook endpoint, create a new webhook, and try again.

**Comment by Knoose** [comment]
@stuboo, I attempted to change mine and my zombie/phantom hooks changed to that new event. I deleted all my hooks yesterday and I'm still getting data for all of them. Till this is fixed, I'm just filtering the incoming hooks on my webserver.

**Comment by stuboo** [comment]
@Knoose Care to share how you're filtering them? Sounds like a good fail safe for my system anyway. I plan to write in a delay of about 30 seconds in the arduino code for each device, but a short delay on my server is a good idea too. Thanks!

**Comment by Knoose** [comment]
@stuboo I'm using Flask (python) and storing the incoming data in a SQL database. Rather than just blindly inserting the incoming values to the database, I added a database query to check if the incoming data matches any value already existing in the database. If it does, I pass over it, and if it doesn't I insert it.

**Comment by brycekahle** [comment]
Thanks for reporting this! I'm having trouble reproducing this issue. Do you have more details that might help me zero in on the problem? If you need to send sensitive information, you can use the community and PM it to `bryce` there.

**Comment by stuboo** [comment]
Bryce,
Does this help? 
https://community.particle.io/t/why-is-my-webhook-request-running-several-times-with-one-call/22598

In setting up my webhook, I created and deleted a webhook named `venus` several times. It seems as though all of those are being called when I call it a single time now. The link above includes the terminal output when I've subscribed and call the hook one time.

Thanks!
Ryan

**Comment by brycekahle** [comment]
@stuboo Yes that helps. Investigating further.

**Comment by Knoose** [comment]
My zombie hooks are all gone now.

**Comment by stuboo** [comment]
Awesome.  Looks like I have one that's still hanging on.  @brycekahle, any updates?

```
{"name":"venus_hook","data":"A3","ttl":"60","published_at":"2016-05-06T13:04:23.016Z","coreid":"my_core_id"}
{"name":"hook-sent/venus_hook","data":"undefined","ttl":"60","published_at":"2016-05-06T13:04:23.038Z","coreid":"particle-internal"}
{"name":"hook-sent/venus_hook","data":"undefined","ttl":"60","published_at":"2016-05-06T13:04:23.039Z","coreid":"particle-internal"}
{"name":"hook-response/venus_hook/0","data":"SUCCESS","ttl":"60","published_at":"2016-05-06T13:04:24.934Z","coreid":"particle-internal"}
{"name":"hook-response/venus_hook/0","data":"SUCCESS","ttl":"60","published_at":"2016-05-06T13:04:24.934Z","coreid":"particle-internal"}
```

**Comment by sazp96** [comment]
I'm still seeing zombie hooks on my logs (two responses for 1 call).

**Comment by brycekahle** [comment]
@stuboo You are running into the prefix filter. Because you have a hook for `venus` and `venus_hook`, when you publish `venus_hook`, both will be triggered. The subscriptions are all prefix filters, meaning they match on the start of the string.

**Comment by brycekahle** [comment]
This issue is still valid btw, but since the webhook system got restarted recently it cleared up the zombie hooks.

**Comment by gritnix** [comment]
Thanks Bryce.  I realize it's a well known issue at this point, but more voices might bump priority so adding mine.  I have zombies as well.  Just getting started on my project so nothing critical for me at this point, just annoying.  Thanks.

**Comment by stuboo** [comment]
Fantastic, everyone. Thanks so much for the work on this. Zombie (and prefix filter) problems resolved for me.

**Comment by pedromorfeu** [comment]
I'm having the same issue. I've deleted all the webhooks and recreated them, but the previous ones are still hanging. It's important to say that I've used the same event name in the recreation process.
I think I'll just wait for the zombies to disappear.

**Comment by budcraig** [comment]
I'm having this issue as well - It is calling 7 total webhooks, 6 deleted and one active. The deleted webhooks are not being listed with particle webhook list, and it has been >48 hrs.

**Comment by pedromorfeu** [comment]
My zombie instances are gone now. They seem to have been cleared during the night.
Just to wrap it all up, what I did was deleting all the webhooks and recreating them. Then it's a matter of time. Anyway, Particle is probably already looking into it.
Thanks everyone.

**Comment by brycekahle** [comment]
We just deployed a fix that should prevent zombies from occurring in the future.
