### ISSUE TITLE
Alert if a .cpp and .ino file have the same name

### ISSUE THREAD

**Issue by osmithy** [spark/particle-cli#253]
I was wrestling with an "undefined reference" error that I knew couldn't be right, and I finally figured out that it was because my .ino file had the same name as one of my .cpp files. When I changed the name of the .ino file, the error went away. My research tells me it's because both the .ino and .cpp files become .o files when compiling, which causes problems when they have the same name. It would be great to have an error for that, given that the "undefined reference" error doesn't make sense to someone who doesn't already know what happens when compiling.

**Comment by monkbroc** [comment]
Issue moved to [spark/cloud #9](https://github.com/spark/cloud/issues/9) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by monkbroc** [comment]
That's a strange error. This should be fixed in the cloud compiler since it also affects the web IDE. I moved it to the repository where we keep issues for cloud components.

**Comment by osmithy** [comment]
Great, thanks for putting it in the right place.
