### ISSUE TITLE
particle list output should not be truncated

### ISSUE THREAD

**Issue by towynlin** [spark/particle-cli#255]
With node 6.2.0 and particle-cli 1.14.1 my `particle list` output is always truncated, excluding function & variable names as well as entire device listings. I'm using zsh 5.0.8, and the output is truncated the same in bash 3.2.57. I verified that doing the bare curl command does in fact list all devices, functions, and variables.

<img width="605" alt="screen shot 2016-06-01 at 7 57 18 am" src="https://cloud.githubusercontent.com/assets/3389/15714351/0aae66ca-27cf-11e6-817d-b43a2ba83aa9.png">

**Comment by monkbroc** [comment]
I couldn't reproduce the issue with node 6.2.0 or 5.11.1, bash or zsh and particle 1.14.1.

If anybody else sees this issue please post here so we can find the cause.

**Comment by wgbartley** [comment]
I can confirm!  @towynlin is not alone.
Mac OS X El Capitan 10.11.5
Bash v3.2.57
NodeJS v6.2.0
Particle CLI v1.14.1

I also have a bonus error in there as well.  I haven't tried tracking it down yet.

<img width="1000" alt="screen shot 2016-06-01 at 4 41 35 pm" src="https://cloud.githubusercontent.com/assets/271242/15725017/caf041d6-2817-11e6-9118-44c420f0dbeb.png">

**Comment by monkbroc** [comment]
The bonus error is from the serialport module :) You upgraded node but the module is still compiled for the old version.

**Comment by wgbartley** [comment]
@monkbroc: I guess attempting another reinstall of particle-cli wasn't enough.

In case it's a character count issue, `particle list | wc -c` gives me `1767`.  I'm not sure if that takes color codes into account, though.

**Comment by brycekahle** [comment]
@wgbartley Try `npm rebuild serialport` to fix the error.

**Comment by brycekahle** [comment]
@wgbartley How did you reinstall?

**Comment by monkbroc** [comment]
This is a race condition between `console.log` dumping its output and the node process shutting down.

**Comment by wgbartley** [comment]
@brycekahle: Node reinstall was compiled from source.  Been doing it that way since before OS packages were available.  Why start now?  I `npm uninstall -g particle-cli`'d and then `npm install -g particle-cli`'d and the previous error is gone.

Let me know if there's anything I can help check on my end.  Ping me in Slack if I don't respond here in a timely manner.

**Comment by dmiddlecamp** [comment]
great find @monkbroc

**Comment by monkbroc** [comment]
I'm just going to make writing to STDOUT blocking for the CLI to fix this and any other similar issues anywhere else in the app.

**Comment by towynlin** [comment]
Fix confirmed! Thanks @monkbroc!
