### ISSUE TITLE
Add WiFi switching to Windows for particle setup

### ISSUE THREAD

**Issue by monkbroc** [spark/particle-cli#258]
`particle setup` is broken on Windows since it can't auto-switch wifi networks. [It also throws an exception right now.](https://community.particle.io/t/cannot-reclaim-particle-photon/23547)

**Comment by brycekahle** [comment]
It is supposed to drop to manual mode on Windows.

**Comment by m-mcgowan** [comment]
Since the setup flow is part of our critical path, let's be sure to add some acceptance tests for this.

**Comment by monkbroc** [comment]
I spent some time last sprint investigating this.

Currently the Wi-Fi handling is done in 2 parts:
- node-wifiscanner2 takes care of the network scanning on macOS, Windows and Linux
- network switching is baked in to the CLI

I would like to push the network switching into a node module, perhaps even the same one (keeping the name or renaming it).

For Windows specifically, it's possible to connect to a different Wi-Fi network with the `netsh wlan connect` command, but only if a "profile" exists for this network. To define a new profile, you need to create an XML file and use `netsh wlan add profile`. I stopped there. I didn't go through with a prototype implementation. It would definitely make more sense to put this functionality and related acceptance tests in its own node module.

**Comment by m-mcgowan** [comment]
:+1: for switching out to a new module. We are surely not the only ones to need this, and testing can be more focused.

**Comment by m-mcgowan** [comment]
There's the SimpleWiFi library that wraps the XML profile creation. It also includes an example console app. We could compile this and bundle the exe with the CLI.
