### ISSUE TITLE
(CLI v1.14.2) particle compile --target 0.5.1

### ISSUE THREAD

**Issue by elevatorguy** [spark/particle-cli#265]
I realize that electron firmware version 0.5.2 is now out, and that I can still compile to 0.5.1 with the web IDE, but it would still be useful to target 0.5.1 from the cli.

**Comment by brycekahle** [comment]
@elevatorguy This is supported (added in #195). It looks like we need to update the documentation.

**Comment by elevatorguy** [comment]
Using version 1.14.2:

![image](https://cloud.githubusercontent.com/assets/881785/16662709/5da163ce-443e-11e6-994f-319e60592b55.png)

**Comment by technobly** [comment]
We just re-added it.  Originally we were going to remove it to keep people from possibly downgrading from it and erasing Wi-Fi credentials, but we decided to handle that case with just warnings in our communications.  Sorry for the inconvenience!
