### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by elevatorguy** [spark/particle-cli#266]
It would be nice to be able to specify the output directory, for example:
particle compile electron --output "D:/path/to/output"

**Comment by brycekahle** [comment]
You can do either:
`particle compile electron . D:/path/to/output`
OR
`particle compile electron --saveTo "D:/path/to/output"`

**Comment by elevatorguy** [comment]
in the meantime i'm doing a batch file on windows

```
cd "D:\code\path"
mkdir bin
copy *.cpp bin
copy *.h bin
copy *.ino bin
cd bin
start cmd /K particle compile electron --target 0.5.1
```
but these does leave source files in the bin directory.

**Comment by Brodan** [comment]
@brycekahle not quite sure what you are talking about. 
running a command with a `--saveTo` flag returns this:
```
I couldn't find that: --saveTo
Compile failed. Exiting.
undefined
```

I'm gonna look into adding this feature myself

**Comment by brycekahle** [comment]
Try `particle compile electron . --saveTo "D:/path/to/output/firmware.bin"`. I forgot you have to specify the filename. I also didn't include the argument of what to compile, `.` (current directory).

**Comment by Brodan** [comment]
@brycekahle ah, it worked when specifying the filename. not sure why this issue is still open then, seeing as how this feature exists.
