### ISSUE TITLE
README is out of date (esp. spark/particle)

### ISSUE THREAD

**Issue by towynlin** [spark/particle-cli#275]

**Comment by m-mcgowan** [comment]
The `README.md` contains details on a few commands in the CLI, while the majority are documented in the CLI documentation at docs.particle.io. The commands outlined in the README will be moved to docs, and a link added to `README.md` for docs and installation.

**Comment by m-mcgowan** [comment]
Moved the README.md into the docs. https://github.com/spark/docs/pull/573
