### ISSUE TITLE
Incorrect key pulled for Electron using TCP

### ISSUE THREAD

**Issue by towynlin** [spark/particle-cli#280]
Given I have an Electron using TCP
When I run `particle keys save electron-key-filename`
Then I expect to receive the RSA key for the TCP server
But instead I currently receive the EC key for the UDP server

**Comment by brycekahle** [comment]
Community member just ran into this bug: https://community.particle.io/t/tls-key-for-local-server-cant-be-converted-to-der-format/27258

**Comment by m-mcgowan** [comment]
The keys commands expects a `--protocol tcp` argument. So, not sure this is a bug other than missing documentation?

So the question is what to do when `--protocol` is not provided. Here's a few options:
- for devices with a single protocol, default to that (current behaviour on Core/Photon/P1)
- for devices with multiple protocol support:
 - raise an error if `--protocol` is not specified. This makes it unambiguous. 
 - or, inspect the device to determine the current protocol in use and default to that, raising the error above if for some reason the protocol cannot be determined.
