### ISSUE TITLE
Getting 'uid must be an unsigned int' error when trying to install or update particle-cli on macOS Sierra

### ISSUE THREAD

**Issue by davidfekke** [spark/particle-cli#284]
Getting 'uid must be an unsigned int' error when trying to install or update particle-cli on macOS Sierra. I am attaching the npm log.
[npm-debug.log.txt](https://github.com/spark/particle-cli/files/492086/npm-debug.log.txt)

Node 6.6
npm 3.10
macOS

**Comment by monkbroc** [comment]
This sound like an issue with npm itself. Take a look at https://github.com/npm/npm/issues/4080

**Comment by m-mcgowan** [comment]
The node issue is closed, so assuming this is fixed for the CLI also. Happy to re-open if that's not the case.
