### ISSUE TITLE
option for override / ignoring bandwidth prompt when flashing electrons?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#287]
I'd like to be able to script flashing firmware to a bunch of electrons, but I can't do that when I get prompted (captcha style) each time.  Can we add some kind of 'forceYes' or some param so I don't get this prompt?

example current behavior:

```
particle flash some_electron
Including:
    firmware.bin

! Flashing firmware Over The Air (OTA) uses cellular data, which may cause you to incur usage charges.
! This flash is estimated to use at least 0.041 MB, but may use more depending on network conditions.

! Please type 0.041 below to confirm you wish to proceed with the OTA flash.
! Any other input will cancel.
? Confirm the amount of data usage in MB: 0.041
attempting to flash firmware to your device some_electron
Flash device OK:  Update started

```

desired behavior:

```
particle flash some_electron --yes
Including:
    firmware.bin

! Skipping Bandwidth Prompt !

attempting to flash firmware to your device some_electron
Flash device OK:  Update started

```

**Comment by nrobinson2000** [comment]
Have you tried using `expect` for now?

You could attempt to flash, fail on purpose, logging the interaction to a file, regex search the file for the number, as it conveniently appears twice, and then spawn the flash process again, inputting the number followed by a new line character using `expect`.

That's how I would script it.

**Comment by m-mcgowan** [comment]
It is - please see the PR above.
