### ISSUE TITLE
`particle serial` not working on Archlinux

### ISSUE THREAD

**Issue by kaihendry** [spark/particle-cli#291]
<img src=http://s.natalian.org/2016-10-25/ps.png>

```
~$ particle --version
1.17.0

```

I don't seem to getting anything back from `/dev/ttyACM0` with my Particle **Internet Button** under 4.8.4-1-ARCH. Is there something I am missing?

**Comment by kennethlimcp** [comment]
Do you see data coming in using other means like screen?

**Comment by kaihendry** [comment]
Oh hai Kenneth :singapore: 

Tried catting the device. No dice. http://s.natalian.org/2016-10-25/debug.png :confounded:

**Comment by kennethlimcp** [comment]
Is your Photon sending serial stuff?

**Comment by kaihendry** [comment]
I expect it to. I want to monitor it and see events when I hit the buttons. Or how do I trigger serial mode?

My aim is to reset it since it seems to have issues reliably staying on my wifi AP.

**Comment by kennethlimcp** [comment]
If your has something like:

```
void setup() {
 Serial.begin(9600);
{

void loop() {
 Serial.println("Hello, World!");
}

then you should be seeing serial output

**Comment by kaihendry** [comment]
Oh, I expect serial to be some sort of debug bridge. If that's not the case, then I guess we should close this?

**Comment by kennethlimcp** [comment]
You can build the debug bridge feature fairly easily so i guess the issue is resolved 👍
