### ISSUE TITLE
Node-serialport not available for node v.51

### ISSUE THREAD

**Issue by sjunnesson** [spark/particle-cli#295]
When running a fresh install for particle-cli with Node v51 it fails since it tries to install node-serialport 3.1.2 which doesn't exists for this node version. Could we update to serialport v4 which has binaries built for node v51?

**Comment by monkbroc** [comment]
Hello,

The serialport module has been a difficult dependency. It has prebuilt binaries for most platforms and most versions of node, but not always. I'm not sure which version you mean by saying v51, but we have people running the CLI with node 0.10, 0.12, 4.x, 5.x, 6.x and 7.x successfully.

**Comment by sjunnesson** [comment]
Node v51 refers to the ABI (application binary interface) version number of Node.js. So that is Node.js v7.1.0

As you can see here https://github.com/EmergingTechnologyAdvisors/node-serialport/releases there is no prebuilt binaries for 3.1.2 of Serialport and Node v51 but just for the 4.0. I pulled down the particle-cli repository and updated the Serialport in the package.json file to 4.0 which then installed nicely and I could get my photon up and running. But not sure if that broke things at other places.

**Comment by monkbroc** [comment]
Thanks a lot for the clarification. We'll take a look at this.

**Comment by iandouglas** [comment]
I'm having the same problem but for Node 7.2, it's trying to download the same serialport version @monkbroc mentions. I'll follow his lead and clone the repo and make that change myself. For some reason I have a Photon which my phone detects with the Particle app, but cannot connect to the Photon, so thought I'd try the CLI.

**Comment by monkbroc** [comment]
Thanks for the comment. Right after the new year I'll review all the dependencies and bump the old ones to avoid further issues like this.

**Comment by m-mcgowan** [comment]
This was fixed in 1.19.0 - https://github.com/spark/particle-cli/commit/722821226057ce63fde57455f78fab371261ae14
