### ISSUE TITLE
`particle setup` flow issues

### ISSUE THREAD

**Issue by technobly** [spark/particle-cli#306]
```
$ particle setup

...
> Requesting public key from the device...
> Setting the magical cloud claim code...
> Telling the Photon to apply your Wi-Fi configuration...
> The Photon will now attempt to connect to your Wi-Fi network...

> Configuration complete! You've just won the internet!
? Would you like to return this computer to the wireless network you just configured? Yes
> It looks like your Photon has made it happily to the cloud!

! PROTIP: Your Photon may start a firmware update immediately upon connecting for the first time.
! PROTIP: If it starts an update, you will see it flash MAGENTA until the update has completed.

...
```

After entering Wi-Fi credentials manually or automatically during the setup command, the Photon connects to the cloud and you are left answering a question:

    ? Would you like to return this computer to the wireless network you just configured?

If you answer `Yes`, it does this for you.  If you answer `No`, it expects you to do the same thing manually before it proceeds.

Shouldn't it just try to do that automatically and if it errors, prompt the user to do it manually?

However, the real question being asked is, "do you want to connect your computer to the wifi credentials you just gave your Photon... so they are then both on the same network? Or do you want me to restore the network you were connected to before running setup?" This shouldn't even be the question though, even if your computer was on a different network.  And in most cases shouldn't be the same network because the Photon is limited to a 2.4GHz network while you want your computer typically to be on a 5GHz network.  They are both on the internet, so the rest of the setup flow will work just fine regardless of which network you are on.

I can't think of any reason why you wouldn't want the CLI to remember the network your computer was previously connected to, and just reconnect it to that after setup.  If for some reason you really want to switch it to a different one, you can do that yourself.

Furthermore, this setup flow slows things down and is fairly confusing without giving the user context of what network we were previously connected to and if that differs from the one we just gave our device.

---

While you are trying to figure this out, the Photon has already connected to the internet and is potentially downloading an update and flashing magenta.  Yet the message about this was not delivered to the user until after the user figures out how to get their computer back on their network.  The PROTIP about this update process should be delivered beforehand.

---

It also claims `> Configuration complete! You've just won the internet!` despite knowing for sure whether the Photon actually connected to the Cloud.  If you enter bad credentials, you get the same false positive.  I don't think this Configuration complete is even necessary at any point, because there are other indicators that the Photon has connected successfully, and configuration is not actually complete until you name the device.  Also at the end of everything, it repeats a similar message `> Congratulations! You've just won the internet!`

---

Here is a suggested flow:

```
$ particle setup

...
> Requesting public key from the device...
> Setting the magical cloud claim code...
> Telling the Photon to apply your Wi-Fi configuration...
> The Photon will now attempt to connect to your Wi-Fi network...

! PROTIP: Your Photon may start a firmware update immediately upon connecting for the first time.
! PROTIP: If it starts an update, you will see it flash MAGENTA until the update has completed.

> Automatically returning your computer to the previous network [ ADD_USERS_SSID_HERE ] ...
> It looks like your Photon has made it happily to the cloud!

? What would you like to call your photon? photon_carloop

> Your Photon has been bestowed with the name photon_carloop
> Congratulations! You've just won the internet!

> Ok, bye! Don't forget `particle help` if you're stuck! <3
...
```

cc: @jenesaisdiq

**Comment by monkbroc** [comment]
Nice writeup. Thanks Brett.

**Comment by alan707** [comment]
I actually found a bug in this flow which took me a long time to figure out.  If you were previously logged in but your token is invalid, it will go through all the steps but fail after successfully detecting a Photon on USB.  

It would be nice if the Particle CLI checked for the token before this step.

**Comment by monkbroc** [comment]
Thanks for the clarification!
