### ISSUE TITLE
Apply the CC3000 patch clarification please

### ISSUE THREAD

**Issue by versamodule** [spark/particle-cli#307]
Could you please clarify something for me. 
Under "Apply the CC3000 patch" it says in step #3, Run particle flash --usb cc3000.
In the Binaries folder I see 2 files
cc3000-patch-programmer.bin & cc3000-patch-programmer_1_14.bin

I am unclear if #3 is a typo, and if so which one of these files should I really use. 

I need to update everything manually, because the Photons I am using will never have their Wi-Fi turned on to get any updates.

**Comment by technobly** [comment]
You do not need to run this command for Photons, only Cores.  And in that case I would stick with the default `particle flash --usb cc3000` which applies `cc3000-patch-programmer.bin`.  Please close the issue if this resolves things for you ;-)
