### ISSUE TITLE
ParticleCLISetup for Windows broken due to OpenSSL download problem

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#328]
Seen and confirmed it this thread
https://community.particle.io/t/particle-cli-installer-win10-installation-aborted-for-openssl/28891

**Comment by monkbroc** [comment]
I released a new installer to fix this. See https://github.com/spark/particle-cli-wrapper/commit/42638070fc9069e96426d916e56587c5ef09d140 for the magic sauce.

Feel free to keep opening issues related to the CLI installer here. The repo for the CLI wrapper & installer doesn't have the visibility of this one.
