### ISSUE TITLE
library create/migrate should provide a library.properties file with ALL fields

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#336]
The Arduino libraries format has loads more fields in `library.properties` which most people won't be aware of.
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

So when creating or migrating a library all these fields should be created as stubs at least.
e.g. the `category` field would be good for filtering libraries as mentioned here
https://community.particle.io/t/introducing-our-new-firmware-library-manager/28790/21

Requiring a properly populated `category` field during validation of a library might also be worth a thought.

**Comment by monkbroc** [comment]
Thanks for that. Library create has a bunch of stubs. We definitely should do the same with migrate.

```
# Fill in information about your library then remove # from the start of lines
# https://docs.particle.io/guide/tools-and-features/libraries/#library-properties-fields
name=new1
version=1.0.0
author=JV
# license=insert your choice of license here
# sentence=one sentence description of this library
# paragraph=a longer description of this library
# url=the URL of the project, like https://github.com/mygithub_user/my_repo
# repository=git repository for the project, like https://github.com/mygithub_user/my_repo.git
# architectures=a list of supported boards if this library is hardware dependent, like particle-photon,particle-electron
```
