### ISSUE TITLE
Fancy UI for new version

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#337]
Everyone loves good UI and this caught my eye to get me updating.<3

Something that we might want to consider?

<img width="343" alt="screen shot 2017-02-05 at 22 42 44" src="https://cloud.githubusercontent.com/assets/6760914/22627013/bc77d780-ebf4-11e6-9692-9d73f230c595.png">

**Comment by m-mcgowan** [comment]
Totally - we have some use of colour in some commands, but could definitely use some refreshing of old commands like version, same for help.

**Comment by kennethlimcp** [comment]
Firebase uses this package: `update-notifier` but i guess we can format it ourselves :)

**Comment by m-mcgowan** [comment]
The CLI recently got the `no-update-check` flag, I think also a `force-update-check` to force a check would be useful too.

**Comment by m-mcgowan** [comment]
`update-notifier` has many dependencies (over 60) - looks like they are working on this in master, so will wait until the next release to see how large the impact is.
