### ISSUE TITLE
Update lint rules to latest

### ISSUE THREAD

**Issue by monkbroc** [spark/particle-cli#339]
Update eslint-config-particle

Include a rule to allow console. The no-console rule is for long running servers.

**Comment by m-mcgowan** [comment]
For more context: the `eslint-config-particle` package was recently changed. Versions 1.0.6/1.0.7 included a config file in eslint 3 format, which caused linting to fail with a "invalid config format" error on projects still using eslint 2.   1.0.8 addressed this by changing the format back to eslint 2. However, it introduced new rules that cause many `unexpected console` errors (no-console rule), resulting in projects that used to successfully build now failing.
