### ISSUE TITLE
`keys doctor <device_id>` fails when device_id has upper-case letters

### ISSUE THREAD

**Issue by avtolstoy** [spark/particle-cli#350]
```
$ particle --version
1.17.0
```
```
$ particle keys doctor 1A0000000000000000000000
...
attempting to add a new public key for device 1A0000000000000000000000
submitting public key succeeded!
Okay!  New keys in place, your device should restart.
```
At this point the device restarts but still fails to connect

```
$ particle keys doctor 1a0000000000000000000000
...
attempting to add a new public key for device 1a0000000000000000000000
submitting public key succeeded!
Okay!  New keys in place, your device should restart.
```
Now the device can successfully connect to the cloud

The behavior is totally confusing. I would expect `1A0000000000000000000000` and `1a0000000000000000000000` to be equal.

**Comment by m-mcgowan** [comment]
Well, it depends upon your model. If you think of the device ID as a number, then sure, it should be case insensitive. If you think of the device ID as a unique identifier, like a filename, then it's not unreasonable that it's case insensitive. However, to reduce friction, we've made it case insensitive. #321
