### ISSUE TITLE
Readme on main page of particle-cli mostly missing

### ISSUE THREAD

**Issue by jaza-tom** [spark/particle-cli#356]
Hello,

It would appear that the vast majority of the particle-cli documentation from the main github repository for Particle-CLI is missing.

Pretty much everything in the table of contents is a blank link with no content:

![image](https://cloud.githubusercontent.com/assets/22616072/24476270/07e0b962-14a9-11e7-8b0c-e4e4b6b9319a.png)

**Comment by kennethlimcp** [comment]
A recent commit broke it: https://github.com/spark/particle-cli/commit/344848331aeb11a131b5cc5264e89e5c7f624e5d

**Comment by m-mcgowan** [comment]
The documentation has moved to https://docs.particle.io/guide/tools-and-features/cli/photon/
