### ISSUE TITLE
Add an option for WiFi setup that resets to dynamic IP and chip antenna

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#373]
We sometimes get members unable to get their devices onto a new WiFi network and sometimes it's due to previous use of `WiFi.useStaticIP()` and/or `WiFi.selectAntenna(ANT_EXTERNAL)` which they had forgotten, are unaware that this are sticky settings or just got a device given which had been set that way by a previous owner.
So instead of having them flash some reset-firmware, why not offer that as an option for `w` (or `W` if it should avoid distraction in the common procedure)

**Comment by monkbroc** [comment]
This is now available through `particle device doctor`.
