### ISSUE TITLE
`flash` fails while `compile` works fine

### ISSUE THREAD

**Issue by technobly** [spark/particle-cli#381]
### Problem

`particle compile photon` with a v2 library creates a binary which can then be OTA'd to a photon just fine, but `particle flash <photon-device-name>` with the same library results in an error:
https://gist.github.com/timkettering/4fd1dddfc90d3a5812ad985594dbb032

### Steps to reproduce

```
git clone https://github.com/timkettering/paper-lanterns
cd paper-lanterns
particle compile photon // should pass
particle flash <photon-device-name> // should fail
```

- Mac OSX 10.12.6
- CLI version 1.23.1

### Notes

I'm reporting this problem for a user on IRC.  I could not reproduce this issue with the same OS/CLI, but they have seen it happen with different devices and a different Mac with CLI 1.22.0.  They also tried this smaller example and it failed the same way https://gist.github.com/technobly/357d805e959bc5b71eae62c52cd5e038

**Comment by timkettering** [comment]
I'm the user experiencing the issue.  I will attempt a few more use cases to see if I can isolate more variables.

**Comment by monkbroc** [comment]
Alright. Keep us posted.

**Comment by kennethlimcp** [comment]
`git clone https://github.com/timkettering/paper-lanterns` works better since `git@` requires the correct user to clone.

Versions
```
KENMBP:paper-lanterns kennethlimcp$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1211

KENMBP:paper-lanterns kennethlimcp$ p --version
1.23.1
KENMBP:paper-lanterns kennethlimcp$ node --version
v6.11.2
```

Compiling and flashing
```
KENMBP:paper-lanterns kennethlimcp$ pcp

Compiling code for photon

Including:
    src/paper-lanterns.ino
    project.properties
attempting to compile firmware 
downloading binary from: /v1/binaries/599663ba76831b3eb08fa970
saving to: photon_firmware_1503028150306.bin
Memory use: 
   text	   data	    bss	    dec	    hex	filename
  11452	     16	   2024	  13492	   34b4	/workspace/target/workspace.elf

Compile succeeded.
Saved firmware to: /Users/kennethlimcp/Desktop/paper-lanterns/photon_firmware_1503028150306.bin


KENMBP:paper-lanterns kennethlimcp$ pf oled .
Including:
    src/paper-lanterns.ino
    project.properties
attempting to flash firmware to your device oled
Flash device OK:  Update started
```

**Comment by technobly** [comment]
Thanks @kennethlimcp!  _Sorry that's my standard method of interacting with github securely._

**Comment by technobly** [comment]
@kennethlimcp can you try just `pf oled` ... the `.` should not be required and would be interesting if the behavior was different.

**Comment by timkettering** [comment]
### For me - when in project directory and trying to do `particle flash` the device directly. It fails with some compilation errors.

```Sloth:paper-lanterns tim$ particle flash beats-table
Including:
    src/paper-lanterns.ino
    project.properties
attempting to flash firmware to your device beats-table
Flash device failed.
Processing  src/paper-lanterns.ino
Checking library FastLED...
Installing library FastLED 3.1.5 to lib/FastLED ...
Library FastLED 3.1.5 installed.
make -C ../modules/photon/user-part all
make[1]: Entering directory '/firmware/modules/photon/user-part'
make -C ../../../user 
make[2]: Entering directory '/firmware/user'
Building cpp file: src/paper-lanterns.cpp
Invoking: ARM GCC CPP Compiler
mkdir -p ../build/target/user/platform-6-msrc/
arm-none-eabi-gcc -DSTM32_DEVICE -DSTM32F2XX -DPLATFORM_THREADING=1 -DPLATFORM_ID=6 -DPLATFORM_NAME=photon -DUSBD_VID_SPARK=0x2B04 -DUSBD_PID_DFU=0xD006 -DUSBD_PID_CDC=0xC006 -DSPARK_PLATFORM -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=6 -DPRODUCT_FIRMWARE_VERSION=65535 -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DPARTICLE_NO_ARDUINO_COMPATIBILITY=0 -DSYSTEM_VERSION_STRING=0.6.1 -DRELEASE_BUILD -I./inc -I../wiring/inc -I../system/inc -I../services/inc -I../communication/src -I../hal/inc -I../hal/shared -I../hal/src/photon -I../hal/src/stm32f2xx -I../hal/src/stm32 -I../hal/src/photon/api -I../platform/shared/inc -I../platform/MCU/STM32F2xx/STM32_USB_Host_Driver/inc -I../platform/MCU/STM32F2xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F2xx/STM32_USB_OTG_Driver/inc -I../platform/MCU/STM32F2xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F2xx/CMSIS/Include -I../platform/MCU/STM32F2xx/CMSIS/Device/ST/Include -I../dynalib/inc -Isrc -I./libraries -Isrc -Isrc -Isrc -Isrc -Ilib/FastLED/src -I. -MD -MP -MF ../build/target/user/platform-6-msrc/paper-lanterns.o.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DSPARK_PLATFORM_NET=BCM9WCDUSI09 -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc  -DLOG_INCLUDE_SOURCE_INFO=1 -DPARTICLE_USER_MODULE -DUSE_THREADING=0 -DUSE_SPI=SPI -DUSE_CS=A2 -DUSE_SPI=SPI -DUSE_CS=A2 -DUSE_THREADING=0 -DUSER_FIRMWARE_IMAGE_SIZE=0x20000 -DUSER_FIRMWARE_IMAGE_LOCATION=0x80A0000 -DMODULAR_FIRMWARE=1 -DMODULE_VERSION=4 -DMODULE_FUNCTION=5 -DMODULE_INDEX=1 -DMODULE_DEPENDENCY=4,2,105 -D_WINSOCK_H -D_GNU_SOURCE -DLOG_MODULE_CATEGORY="\"app\""  -fno-exceptions -fno-rtti -fcheck-new -std=gnu++11 -c -o ../build/target/user/platform-6-msrc/paper-lanterns.o src/paper-lanterns.cpp
In file included from src/paper-lanterns.ino:1:0:
lib/FastLED/src/FastLED.h:12:2: warning: #warning FastLED version 3001000 (Not really a warning, just telling you here.) [-Wcpp]
 #warning FastLED version 3001000  (Not really a warning, just telling you here.)
  ^
In file included from lib/FastLED/src/led_sysdefs.h:16:0,
                 from lib/FastLED/src/FastLED.h:34,
                 from src/paper-lanterns.ino:1:
lib/FastLED/src/led_sysdefs_arm_stm32.h:26:0: warning: "cli" redefined [enabled by default]
 #define cli()  __disable_irq(); __disable_fault_irq();
 ^
In file included from ./inc/application.h:92:0,
                 from src/paper-lanterns.cpp:1:
../wiring/inc/spark_wiring_arduino.h:141:0: note: this is the location of the previous definition
 #define cli() (void)HAL_disable_irq()
 ^
In file included from lib/FastLED/src/led_sysdefs.h:16:0,
                 from lib/FastLED/src/FastLED.h:34,
                 from src/paper-lanterns.ino:1:
lib/FastLED/src/led_sysdefs_arm_stm32.h:27:0: warning: "sei" redefined [enabled by default]
 #define sei() __enable_irq(); __enable_fault_irq();
 ^
In file included from ./inc/application.h:92:0,
                 from src/paper-lanterns.cpp:1:
../wiring/inc/spark_wiring_arduino.h:136:0: note: this is the location of the previous definition
 #define sei() HAL_enable_irq(0)
 ^
In file included from lib/FastLED/src/led_sysdefs.h:16:0,
                 from lib/FastLED/src/FastLED.h:34,
                 from src/paper-lanterns.ino:1:
lib/FastLED/src/led_sysdefs_arm_stm32.h:36:32: error: conflicting declaration 'typedef volatile uint8_t RwReg'
 typedef volatile       uint8_t RwReg; /**< Read-Write 8-bit register (volatile unsigned int) */
                                ^
In file included from ./inc/application.h:92:0,
                 from src/paper-lanterns.cpp:1:
../wiring/inc/spark_wiring_arduino.h:153:27: error: 'RwReg' has a previous declaration as 'typedef volatile uint32_t RwReg'
 typedef volatile uint32_t RwReg;
                           ^
../build/module.mk:267: recipe for target '../build/target/user/platform-6-msrc/paper-lanterns.o' failed
make[2]: Leaving directory '/firmware/user'
make[2]: *** [../build/target/user/platform-6-msrc/paper-lanterns.o] Error 1
../../../build/recurse.mk:11: recipe for target 'user' failed
make[1]: *** [user] Error 2
make[1]: Leaving directory '/firmware/modules/photon/user-part'
```

### However - doing `particle compile photon` succeeds.  Flashing the device using the `.bin` file succeeds as well.

```Sloth:paper-lanterns tim$ particle compile photon

Compiling code for photon

Including:
    src/paper-lanterns.ino
    project.properties
attempting to compile firmware 
downloading binary from: /v1/binaries/5997090616ed5760fce5968a
saving to: photon_firmware_1503070457321.bin
Memory use: 
   text	   data	    bss	    dec	    hex	filename
  13564	     16	   2156	  15736	   3d78	/workspace/target/workspace.elf

Compile succeeded.
Saved firmware to: /Users/tim/Development/Particle/paper-lanterns/photon_firmware_1503070457321.bin```

**Comment by kennethlimcp** [comment]
i wonder...

```
KENMBP:paper-lanterns kennethlimcp$ pf oled
Including:
    src/paper-lanterns.ino
    project.properties
attempting to flash firmware to your device oled
Flash device OK:  Update started
KENMBP:paper-lanterns kennethlimcp$ 
```

**Comment by technobly** [comment]
Thanks for trying... yeah, nothing to see there.

**Comment by monkbroc** [comment]
@timkettering Here's something to try. Open the Web IDE at build.particle.io, open the devices tab, click the arrow next to your device name and see what it says under System firmware target and On the device.

My thought is that your device firmware target is pinned to an old system firmware version so when you do `particle compile` it works because that uses the latest version by default, but when you do `particle flash` it tries to respect the system firmware version you had selected a long time ago.

To fix this, select "On the device" in the system firmware version selector.

**Comment by timkettering** [comment]
@monkbroc - hi.. thank you for the info.  i checked the device on build.particle.io and it does show that the system firmware target is 0.6.1 and **on device** showed as 0.6.2.  

i clicked the dropdown for system firmware target and changed it to 0.6.2 to match the on device version and then tried running the `particle flash` on the command line again but unfortunately it still failed with same compilation error.

i am unsure how the web IDE would affect the compilation target that CLI uses, unless this is more cloud-side?

but hopefully this is a good first step in resolving the issue!

**Comment by monkbroc** [comment]
Hum. Try to force the target firmware to be 0.6.2 then. `particle flash beats-table . --target 0.6.2`

**Comment by technobly** [comment]
>i am unsure how the web IDE would affect the compilation target that CLI uses, unless this is more cloud-side?

The CLI uses the "pinned build target" for the device you select (in this case beats-table), unless you force a different `--target ver`.  

You can also try setting the build target to `default 0.6.2` which will update automatically over time to the latest default build target (this is the preferred option to get the latest bug fixes and features).  This will exclude prereleases.

**Comment by timkettering** [comment]
@monkbroc @technobly - adding the `--target 0.6.2` worked.  it flashed successfully.

in the devices list on the webIDE, it shows beats-table device with version 0.6.2 but looks like there is a value out of place or out of sync when coming from `particle flash`

**Comment by monkbroc** [comment]
I'm glad it's working for you. I'll continue investigating internally why your device is in this weird state.

**Comment by timkettering** [comment]
Just to make sure nothing else changed, I verified the target and device versions:  (see screenshot below).

I ran both `particle flash beats-table .` and `particle flash beats-table . --target 0.6.2`  ..  former one failed w/ the compilation error, the latter succeeded.


<img width="310" alt="screenshot 2017-08-18 13 38 36" src="https://user-images.githubusercontent.com/272658/29476824-9f372c20-841a-11e7-8166-fc272d1005af.png">

**Comment by monkbroc** [comment]
Can you switch that dropdown to **On the device (0.6.2)**

**Comment by monkbroc** [comment]
I changed your device on our backend so this problem should be completely gone for you. I'll close this issue and I'll continue investigating internally to figure out how your device got into this weird state and what we can do to prevent other devices from going into this weird state.
