### ISSUE TITLE
particle compile: Setting output filename doesn't work

### ISSUE THREAD

**Issue by JSchaenzle** [spark/particle-cli#383]
The help content says:
```
USE:
    particle compile device_type firmware.bin
    particle compile device_type source_folder
    particle compile device_type file1.ino file2.cpp file2.h file3.cpp
```
The first one seems to indicate that I can specify the output filename.
If i run `particle compile photon foo.bin` I get the following output:
```
Compiling code for photon
I couldn't find that: foo.bin
Compile failed. Exiting.
undefined
```
Am I doing something wrong or is the `compile` command broken?

**Comment by monkbroc** [comment]
We need to fix the help. The syntax to specify the filename is `--saveTo filename.bin`
If you're compiling the current folder do `particle compile photon . --saveTo filename.bin`
