### ISSUE TITLE
Update tinker binary

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#4]
1. There should be a user-part only tinker for Photon since it's supporting fast OTA of only user code now

2. The better option might be to check which device you are trying to flash and select the correct tinker binary from the :cloud: or local copy. 

- If it is a core, use a tinker firmware with the full tinker firmware compiled for core
- If it is a photon, flash a user-part tinker

3. change the name from `spark_tinker.bin` to `particle_tinker.bin`

**Comment by emilyrose** [comment]
I believe you fixed this, no? :smile:
