### ISSUE TITLE
particle compile exit code

### ISSUE THREAD

**Issue by Rockvole** [spark/particle-cli#44]
Would it be possible to have particle compile return a different exit code on success or failure ?
Looks like it always returns 0

The same as gcc would work :

http://stackoverflow.com/questions/1024525/how-to-check-if-gcc-has-failed-returned-a-warning-or-succeeded-in-bash

Its helpful when writing shell scripts.

**Comment by loopj** [comment]
:+1: this would be super helpful for custom buildchains

**Comment by kennethlimcp** [comment]
@Rockvole , do you have more concrete example for this? I see that the CLI will throw an error when compile fails. How are you using it to detect the exit code?

**Comment by loopj** [comment]
An obvious use case is for running particle compile in a Makefile, since by default a Makefile will not run subsequent tasks if any previous tasks exit with a non-zero exit status.

**Comment by kennethlimcp** [comment]
Cool. i can look into that :+1:

**Comment by Rockvole** [comment]
Yes thats basically my use case - compile and then flash, if the build fails dont flash and dont ask me for my sudo password.

**Comment by kennethlimcp** [comment]
@Rockvole, do you have a working script? I used a shell script and got the `console.log` stuff as my output from `$(particle compile photon .)` instead but not the return code.

I see that we might need to use some other stuff like `process.exit()` in order to return a status

**Comment by Rockvole** [comment]
Yes, this is how I would use it :

```
#! /bin/bash
echo ------------------------------------------------------------------- build
particle compile . --saveTo firmware.bin

if [ "$?" = "0" ]; then
  echo ------------------------------------------------------------------- check usb
  sudo dfu-util -l

  echo ------------------------------------------------------------------- flash
  sudo particle flash --usb firmware.bin
  rm firmware.bin
else
  echo Build Fail
fi
```

**Comment by emilyrose** [comment]
This sounds like exactly the kind of use case I'd like to support, so just let me know what we want to do here and I will try to make it work!

**Comment by Rockvole** [comment]
For my use case return exit code 0 for a successful build and return exit code 1 for fail is fine.

Its up to you if you want to get more fancy with different codes for different types
of failure, or returning a meaningful error code, but I don't think I need that myself.

**Comment by loopj** [comment]
*1

**Comment by emilyrose** [comment]
@Rockvole @loopj this sounds reasonable, and frankly I apologize for not having thought of this sooner!

Thanks for the feedback, I'll make sure this gets fixed. :smile_cat:

**Comment by brycekahle** [comment]
Looks like this was fixed with https://github.com/spark/particle-cli/commit/60afa74fa1189c2efa40f553b435494fbe9969dd
