### ISSUE TITLE
[Photon] `particle setup` fails on OSX due to hardcoded Wi-Fi interface

### ISSUE THREAD

**Issue by siddMahen** [spark/particle-cli#48]
I just received my Photon today. After connecting it to my computer via USB, installing the particle cli and running `particle setup`, I encountered the following problem:

```
! Woops. Something went wrong connecting to Photon-JTTY. Please manually re-connect to your Wi-Fi network.
```

After digging through the code, I isolated the problem to a bug in WirelessCommand/connect/darwin.js:

```
	var params = 'networksetup -setairportnetwork en0 ' + opts.ssid;
	if(opts.password) { params += ' ' + opts.password; }

	// TODO: something with opts & interfaces?
	exec(params, results);
	function results(err, stdin, stderr) {

		if(err || stderr) {

			// TODO: more research into failure modes of this command
			return cb(err || stderr);
		}
		cb(null, opts);
	};
```

Here, the particle cli is trying to connect to a particular Wi-Fi network using the `networksetup` utility. The problem is that on certain Darwin machines, `en0` is not a valid Wi-Fi interface, and thus this method fails every time it's called. In turn, this causes the following code in WirelessCommand/index.js to consistently fail:

```
		if(!self.__manual) {

			self.newSpin('Attempting to connect to ' + photon + '...').start();
			mgr.connect({ ssid: photon }, connected);
		}

...

	function connected(err, opts) {

		self.stopSpin();
		if(err) {
			// TODO: Max retries, help output when reached.
			console.log(
				chalk.bold.red('!'),
				chalk.bold.white('Woops. Something went wrong connecting to ' + photon + '. Please manually re-connect to your Wi-Fi network.')
			);
			return;
		}
		console.log(
			arrow,
			'Hey! We successfully connected to',
			chalk.bold.cyan(opts.ssid)
		);
		self.__configure(opts.ssid, done);
	};
```

Running `networksetup -listallhardwareports` shows me that `en1` is the correct hardware port for the Wi-Fi interface on my machine:

```
$  ~  networksetup -listallhardwareports

Hardware Port: Bluetooth DUN
Device: Bluetooth-Modem
Ethernet Address: N/A

Hardware Port: Ethernet
Device: en0
Ethernet Address: ac:87:a3:2e:bf:ef

Hardware Port: Wi-Fi
Device: en1
Ethernet Address: b8:09:8a:d3:5e:2f

Hardware Port: Bluetooth PAN
Device: en4
Ethernet Address: b8:09:8a:d3:5e:30

Hardware Port: Thunderbolt 1
Device: en2
Ethernet Address: 32:00:1a:a0:80:00

Hardware Port: Thunderbolt 2
Device: en3
Ethernet Address: 32:00:1a:a0:80:01

Hardware Port: Thunderbolt Bridge
Device: bridge0
Ethernet Address: N/A

VLAN Configurations
===================
```

Changing `en0` to `en1` allowed me to complete `particle setup` without any further trouble.

Fixing this issue would require a reliable method of obtaining the correct hardware port. Parsing the output of `networksetup -listallhardwareports` or `networksetup -listnetworkserviceorder` seems to work, but this is ugly.

**Comment by dmiddlecamp** [comment]
awesome bug report, thank you! :+1:

**Comment by emilyrose** [comment]
@siddMahen thanks a lot for such a detailed report!

I will make this a high priority to fix. Thank you so much!

**Comment by brycekahle** [comment]
I think we can use `networksetup -listallhardwareports` and find all ports with `Wi-Fi` in the `Hardware Port`.

Example output:
```
Hardware Port: Bluetooth DUN
Device: Bluetooth-Modem
Ethernet Address: N/A

Hardware Port: Wi-Fi
Device: en0
Ethernet Address: 34:36:3b:d2:fb:3e
```
