### ISSUE TITLE
undefined "writeKeyToCore" and "saveKeyFromCore" function

### ISSUE THREAD

**Issue by endorama** [spark/particle-cli#49]
Seems like there are 2 unrenamed functions in `KeyCommands.js` in the latest master.

* `writeKeyToCore`: 
[commands/KeyCommands.js:286](https://github.com/spark/particle-cli/blob/f75ff64ea88c8205b3d5bfee5ef5677c9107343d/commands/KeyCommands.js#L286) is line
`return that.writeKeyToCore(deviceid + "_new", true);`
* `saveKeyFromCore`: [commands/KeyCommands.js:164](https://github.com/spark/particle-cli/blob/f75ff64ea88c8205b3d5bfee5ef5677c9107343d/commands/KeyCommands.js#L164) is `return that.saveKeyFromCore(prefilename);`

Replacing those instances with `writeKeyToDevice` and `saveKeyFromDevice` made everything works again.

I could submit a PR for this, in case is needed.

**Comment by emilyrose** [comment]
@endorama, thanks for the bug report!

If you'd like to submit a PR, that would certainly be welcome! Otherwise, I am happy to fix this myself.

Let me know what you think!

**Comment by endorama** [comment]
Pull request ready!

PS: I read from contribution guidelines that I should sign the Spark Individual Contributor License Agreement (CLA). Should I simply fill the GDocs form?

**Comment by emilyrose** [comment]
@endorama correct! Just fill out this form if you will: https://docs.google.com/a/particle.io/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform

Thank you so much! :smile_cat:

**Comment by endorama** [comment]
Form filled, please let me know if further steps should be taken.

**Comment by emilyrose** [comment]
that's it! thanks so much!
