### ISSUE TITLE
`particle setup` doesn't work for a core

### ISSUE THREAD

**Issue by joegoggins** [spark/particle-cli#5]
Setup process is broken for the Spark Core. Saw this issue on released 1.5.6 and 1.5.8. To reproduce error:

1. `particle setup`
2. `Would you like to log in with a different account? No`
3. The program just exits, instead of proceeding to setup the core.

I did this with the CLI configured to the staging cloud (in case it's relevant)

**Comment by beroe** [comment]
I am currently having the same problem with a Spark Core. I was able to set up a few new photons, but the core has the symptoms described above. This is with CLI version v1.5.10

If I do `ls /dev/tty*` I see it listed as  `/dev/tty.usbmodem1411`

I will try firmware update next.

**Comment by brycekahle** [comment]
Dup of #13 and fixed in 1.5.11

**Comment by joegoggins** [comment]
Fix confirmed here too, all I had to do was run `npm update -g particle-cli` and run `particle setup` again with a Core plugged in and in listening mode and poof, it worked as expected.

Thanks @brycekahle , much appreciated!

**Comment by dmiddlecamp** [comment]
:boom: Thanks @brycekahle !
