### ISSUE TITLE
Incomplete use of 'sudo' when running 'dfu-util'

### ISSUE THREAD

**Issue by endorama** [spark/particle-cli#51]
In my setup I need to use `sudo` to properly run `dfu-util -l` ( the setup has been created following the [guide provided](https://community.particle.io/t/how-to-install-spark-cli-on-ubuntu-12-04/3474) in the Readme of this repository ).

There is a configuration option ( `useSudoForDfu` ) that I presume should be used in this cases, but currently  doesn't run `dfu-util -l` with `sudo` ( actually is used only for **reading** from the device, not for listing or writing ), as you can see from the lines in `lib/dfu.js`:
* [lib/dfu.js line 44](https://github.com/spark/particle-cli/blob/88ea621d2ea64aa85c112efc4d0a91a6d6634799/lib/dfu.js#L44)
* [lib/dfu.js line 87](https://github.com/spark/particle-cli/blob/88ea621d2ea64aa85c112efc4d0a91a6d6634799/lib/dfu.js#L87)
* [lib/dfu.js line 111](https://github.com/spark/particle-cli/blob/88ea621d2ea64aa85c112efc4d0a91a6d6634799/lib/dfu.js#L111)
* [lib/dfu.js line 93](https://github.com/spark/particle-cli/blob/88ea621d2ea64aa85c112efc4d0a91a6d6634799/lib/dfu.js#L93) where `getCommandPrefix` is run and returns `sudo dfu-util` if `useSudoForDfu` is true

This makes the commands like `keys` crash ( in particular I wasn't able to complete step 7 of spark-server installation process ).

Is this the intended behaviour? I tried changing the code to use sudo and everything seemed to work fine.

I can submit a PR to fix this.
Thank you

**Comment by kennethlimcp** [comment]
@endorama , do you have a PR? Or i can fix this :)

**Comment by endorama** [comment]
PR submitted! :)

**Comment by emilyrose** [comment]
yay! thanks @endorama! :heart:
