### ISSUE TITLE
particle device rename doesn't successfully save multi-word names

### ISSUE THREAD

**Issue by jme783** [spark/particle-cli#52]
```
$ particle device rename 2d00XXXXXXXXXXXXXX Stagey Stage Photon
Renaming device 2d00XXXXXXXXXXXXXX
Successfully renamed device 2d00XXXXXXXXXXXXXX  to: Stagey
```

Note that the device should be named "Stagey Stage Photon"

**Comment by dmiddlecamp** [comment]
I would argue we should not allow multi-word names, since they're used in URLs

**Comment by dmiddlecamp** [comment]
@jme783 --> should this be an issue for the API, since this isn't a supported feature?

**Comment by joegoggins** [comment]
What if the cli did a search and replace for all non- a-z 0-9 _ characters to - ? On match, it could warn the user that it choose a slightly different name.

**Comment by jme783** [comment]
Interesting, didn't realize that we didn't support it. I like @joegoggins idea of a smart replace. At the very minimum the CLI should tell the user that they can't use multiple words for their name

**Comment by kennethlimcp** [comment]
It's tricky for a CLI unless you did a `particle device rename xxxx "xxxx xxxx xxx"` Without the quotes, each part of the name is another argument.

We can always count but it becomes too much work just to get that smart thing going

**Comment by joegoggins** [comment]
Yea, it'd probably better to just fail if more than 2 arguments were
passed.  Actually, that would be a handy feature for many other
sub-commands as well; a general ability to fail if the wrong number of
arguments are passed, option ordering is wrong or not supported, etc.
Thor <http://whatisthor.com/>, the command line utility behind tons of Ruby
CLI tools like travis, heroku, and many others do this really well, I
wonder if there is something similar in npm we could use to do this.
