### ISSUE TITLE
Travis CI warnings / issues

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#53]
Our firmware build is using Travis and the CLI to do test builds, but it looks like maybe something is off about the two combined.  Any chance we can fix this part of the build?  Is it just a matter of not using the deprecated module, and using the new one?

https://travis-ci.org/spark/firmware/builds/64131560

Thanks! :)

edit: reviewed this some more, looks like the CLI is adapting and skipping modules it can't find dependencies for.  Looks like the thing failing the build is:

```
!!! Install it now by running npm install -g particle-cli
12580
spark variable did not return an integer. Network connectivity problems?
```

**Comment by brycekahle** [comment]
I would recommend trying `particle-cli`. We haven't updated `spark-cli` in quite awhile.

**Comment by kennethlimcp** [comment]
The error came from here - https://github.com/spark/firmware/blob/e28f4256ba132f788d07eb39af4e511745568e88/ci/test_memory_available_with_real_core.sh#L99

There needs to be an actual CI core setup for the test and the output means there's probably not one online
