### ISSUE TITLE
`particle setup wifi` often fails on Core

### ISSUE THREAD

**Issue by pomplesiegel** [spark/particle-cli#56]
On our cores running a FW program w/ WiFi in MANUAL_MODE, if we 
1. Place an already happy/connected core running our FW into listening mode
2. run `particle setup wifi` and enter SSID, Security, PW
we time out w/ the message:
`Attempting to configure Wi-Fi on /dev/cu.usbmodem1411`
`I said: w`
`timed out on SSID:`
`Something went wrong Serial prompt timed out - Please try restarting your device`

At this time the Core's LED either goes blank or becomes solid blue, and wifi credentials are not transferred.

**Comment by kennethlimcp** [comment]
I rarely ever had issues with the core. Are you on the latest CLI version?

**Comment by pomplesiegel** [comment]
Yes, currently using 1.5.16, but we have seen this pop up all throughout the past months of development (since about January). We can reproduce this on nearly all our Cores at any given time. They all have deep_update_2014_06 and cc3000 v1.29. 

Only unique attribute of our code from a WiFi perspective is that we're using MANUAL_MODE.

**Comment by kennethlimcp** [comment]
Are you using local compile as well If so, which branch and version?

I don't think that MANUAL mode really matters since the Core is in listening mode for that to work.

Unless you tried running that command without the Core in listening mode which explains why it timed out.

**Comment by pomplesiegel** [comment]
We're using remote compile. I figured MANUAL_MODE wouldn't matter, as you said, it gets put in listening mode anyway.
We definitely have the core blinking blue when attempting to run `particle setup wifi`. I've tried clearing the cc3000 creds as well, but that makes no difference. Haven't seen this at all?

**Comment by emilyrose** [comment]
@pomplesiegel what happens when you have the Core in listening mode and use `particle serial wifi`?

**Comment by pomplesiegel** [comment]
@emilyrose, same timeout behavior seen with `particle serial wifi`. FYI, I just tried `particle setup wifi` and the first two times passed, and all subsequent calls failed. That's when I tried `particle serial wifi`, which also failed.

**Comment by kennethlimcp** [comment]
@pomplesiegel , i'm not if it is a cable issue that you are having.

Can you try loading the tinker firmware using `particle flash --usb tinker` and do stuff like `particle serial identify` or `particle serial wifi`?

If both doesn't work when the Core is blinking blue, there's a high chance it's a cable issue or driver issue. Check that the Core appears as a COM port when you do that. 

Also, do you happen to be on linux?

**Comment by pomplesiegel** [comment]
@kennethlimcp 
* just tried a brand new spark-issued cable and the same issue occurred. 
* Interesting! W/ the exact same HW setup which was failing w/ our program running, I have now 100% success rate when tinker is loaded. 
* Loaded our program again, and the same timeout + (Core's LED turns off or solid blue) issue occurs.

Only thing our program does to manipulate the serial port is`Serial.begin(9600);`

FYI, `particle serial identify` is also sometimes failing w/ our binary loaded and the Core in listening mode:
`! serial: Serial timed out
Potentially unhandled rejection`
`[2] Serial timed out (WARNING: non-Error used)`

**Comment by kennethlimcp** [comment]
Did you compile the binary using the Particle Cloud?

Honestly, 1 year and i never had such issues with the Core. I can test if you have the bin to share

**Comment by pomplesiegel** [comment]
Strange!

Yes, I am compiling the binary using the particle cloud. Happy to share the binary! FYI, the program, itself, will not run nicely, as it expects many i2c peripherals (on our motherboard) to be present at boot-up time. However, that should not matter, as you need only to place it in listening mode. 

How shall I send you the file?

**Comment by kennethlimcp** [comment]
You can PM me in the forum or drop me an email stated on my github profile.

**Comment by pomplesiegel** [comment]
Great, sending now. thanks!

**Comment by kennethlimcp** [comment]
@pomplesiegel , as this is more of a firmware issue, do consider closing this if all is good :)

**Comment by pomplesiegel** [comment]
Sure, @kennethlimcp. I'll try to close in on the problem a bit more and add a FW issue.
