### ISSUE TITLE
Error when compiling: Target device blinky.ino is not valid

### ISSUE THREAD

**Issue by osmithy** [spark/particle-cli#58]
There probably some obvious thing I'm missing, but I cannot find a single page on the internet about this error.

When I navigate to the directory containing blinky.ino and type `particle compile blinky.ino` I get the error `Target device blinky.ino is not valid`

This happens with any sketch I try.

Interestingly, if I substitute `flash [my device name]` in place of `compile`, it compiles and flashes.

**Comment by osmithy** [comment]
Interestingly, if I substitute `flash [my device name]` in place of `compile`, it compiles.

**Comment by emilyrose** [comment]
hey @osmithy, thanks for the report! I will be looking into this.

**Comment by osmithy** [comment]
Thanks!!

**Comment by osmithy** [comment]
Apparently you need to specify whether it's a core or photon. The
documentation just needs to be updated to reflect that.

particle compile mycode fails

particle compile photon mycode succeeds

Update this doc:
http://docs.particle.io/photon/cli/#update-your-device-remotely

**Comment by dmiddlecamp** [comment]
hmm, that's a pretty major change for this command, we should make this an optional param right, so we don't break people who are using it currently?

**Comment by kennethlimcp** [comment]
@emilyrose, PR here is waiting for review - https://github.com/spark/particle-cli/pull/55

@dmiddlecamp i'm against making this optional with electron upcoming. It will cause more confusion and support tickets/github issues opened.

I recommend adding the example here: https://github.com/spark/particle-cli/blob/master/commands/CloudCommands.js#L284

`eg. paticle compile core .`

**Comment by kennethlimcp** [comment]
New PR added here: https://github.com/spark/particle-cli/pull/59

Docs pr to be reviewed: #55

**Comment by emilyrose** [comment]
fixed && fixed! thanks again @kennethlimcp! thanks @osmithy :smile:

**Comment by osmithy** [comment]
You bet! Thank you for being so responsive.
