### ISSUE TITLE
inquirer crash

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#6]
C:\Users\username>particle setup 
_ _ _ _ 
_ __ __ _ _ __| |_(_) ___| | ___ (_) ___ 
| '_ \ / _` | '__| __| |/ __| |/ _ \ | |/ _ \ 
| |_) | (_| | | | |_| | (__| | __/_| | (_) | 
| .__/ \__,_|_| \__|_|\___|_|\___(_)_|\___/ 
|_| https://particle.io/

> Setup is easy! Let's get started... 
? Hello Stranger! This seems to be your first time here. What would you like to 
? Hello Stranger! This seems to be your first time here. What would you like to 
? Hello Stranger! This seems to be your first time here. What would you like to 
do? Login 
> Let's get you logged in! 
? Please enter your email address: username@gmail.com 
? Please enter your password: ********* 
> Successfully completed login!

! PROTIP: Hold the MODE/SETUP button on your device until it blinks blue! 
! PROTIP: Please make sure you are connected to the internet.

> I have detected a Spark Core connected via USB. 
? Would you like to continue with this one? Yes 
? Should I scan for nearby Wi-Fi networks? Yes 
? Select the Wi-Fi network with which you wish to connect your device: (Use arro 
? Select the Wi-Fi network with which you wish to connect your device: lshome 
? Should I try to auto-detect the wireless security type? Yes

C:\Users\username\AppData\Roaming\npm\node_modules\particle-cli\node_modules\in 
quirer\node_modules\rx\dist\rx.js:579 
throw e; 
^ 
TypeError: Cannot call method 'indexOf' of undefined 
at Object.inquirer.prompt.when (C:\Users\username\AppData\Roaming\npm\node_ 
modules\particle-cli\commands\SerialCommand.js:339:60) 
at Object.utils.runAsync (C:\Users\username\AppData\Roaming\npm\node_module 
s\particle-cli\node_modules\inquirer\lib\utils\utils.js:29:22) 
at C:\Users\username\AppData\Roaming\npm\node_modules\particle-cli\node_mod 
ules\inquirer\lib\ui\prompt.js:131:13 
at tryCatcher (C:\Users\username\AppData\Roaming\npm\node_modules\particle- 
cli\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29) 
at setDisposable (C:\Users\username\AppData\Roaming\npm\node_modules\partic 
le-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:4977:36) 
at AnonymousObservable.s [as _subscribe] (C:\Users\username\AppData\Roaming 
\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js: 
4994:11) 
at AnonymousObservable.Rx.Observable.observableProto.subscribe.observablePro 
to.forEach (C:\Users\username\AppData\Roaming\npm\node_modules\particle-cli\nod 
e_modules\inquirer\node_modules\rx\dist\rx.js:2160:19) 
at C:\Users\username\AppData\Roaming\npm\node_modules\particle-cli\node_mod 
ules\inquirer\node_modules\rx\dist\rx.js:2403:21 
at tryCatcher (C:\Users\username\AppData\Roaming\npm\node_modules\particle- 
cli\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29) 
at setDisposable (C:\Users\username\AppData\Roaming\npm\node_modules\partic 
le-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:4977:36)

C:\Users\username>

**Comment by brycekahle** [comment]
My guess is that this crash wasn't actually in `inquirer`. Do you have any more details that might help us locate the bug? What version you were running perhaps?

**Comment by alexanian** [comment]
I get the same error whenever I try to auto detect the wireless security type. Image shown below:
![error](https://cloud.githubusercontent.com/assets/7595169/8913900/cdc60672-3469-11e5-8494-00748592f968.png)

I'm on Windows running git bash as my connection to the particle CLI.

**Comment by emilyrose** [comment]
@alexanian, ack!

Do you still get an error if you choose "no" at the prompt for auto-detecting wireless security type?

**Comment by alexanian** [comment]
Nope, no issue if I just enter "n" and choose the security from the list.
