### ISSUE TITLE
`particle setup` without WiFi card

### ISSUE THREAD

**Issue by javier-rodas** [spark/particle-cli#61]
By default the `particle setup` tries to configure the Photon by WiFi using the Soft-AP mode, but I guess this option should not appear when the computer has no WiFi network interface.

In my case I'm running OSX without a WiFi card, and when running the `particle setup` I would have not other option than choosing `No` to the latest question shown below:

```
$ particle setup
                  _   _      _        _
 _ __   __ _ _ __| |_(_) ___| | ___  (_) ___
| '_ \ / _` | '__| __| |/ __| |/ _ \ | |/ _ \
| |_) | (_| | |  | |_| | (__| |  __/_| | (_) |
| .__/ \__,_|_|   \__|_|\___|_|\___(_)_|\___/
|_|                     https://particle.io/

> Setup is easy! Let's get started...
> It appears as though you are already logged in as xxxxxxxxxxx@xxxxx.xxx
? Would you like to log in with a different account? No

! PROTIP: Hold the MODE/SETUP button on your device until it blinks blue!
! PROTIP: Please make sure you are connected to the internet. 

> I have detected a Photon connected via USB.
? Would you like to continue with this one? Yes
! The Photon supports secure Wi-Fi setup. We'll try that first.

! PROTIP: Wireless setup of Photons works like a wizard!
! PROTIP: We will automagically change the Wi-Fi network to which your computer is connected.
! PROTIP: You may lose your connection to the internet for a moment.

> No nearby Photons detected. Try the `particle help` command for more information.
? Would you like to wait and monitor for Photons entering setup mode? No

> Ok, bye! Don't forget `particle help` if you're stuck! <3
```

If I choose `Yes` to the latest question, the script **attempts forever** to find a Photon by an inexistent WiFi connection:

```
...
? Would you like to wait and monitor for Photons entering setup mode? Yes
> Monitoring nearby Wi-Fi networks for Photons. This may take up to a minute.
* Waiting for a wild Photon to appear... (press ctrl + C to exit)
```

So, if it's not possible to autodetect the presence of a WiFi card in the current computer, why don't you just enter in the manual WiFi credentials setup after choosing `No`in the latest question... as it would apprear when executing `particle setup wifi`:

```
$ particle setup wifi
? Should I scan for nearby Wi-Fi networks? No
? SSID: XXXXXXX
? Security Type: WPA2
? Wi-Fi Password: *********
```

That is, the `particle setup` would make sense at least to continue like this, after choosing `No` in the latest question:

```
...
? Would you like to wait and monitor for Photons entering setup mode? No
? SSID: XXXXXXX
? Security Type: WPA2
? Wi-Fi Password: *********
```

**Comment by emilyrose** [comment]
@javier-rodas, thank you for the suggestion! I will be working on improving the logic around automagic Wi-Fi and manual modes. I think you propose a sensible way to handle this better.

**Comment by brycekahle** [comment]
One thing to note is that we cannot configure a claim code over serial, so we would need to initiate the old claim process (`device add`) once the device is online.

**Comment by m-mcgowan** [comment]
The claim code over serial is supported from firmware version 0.6.0-rc.1, so we could use the new claim process over serial.  We can also set the claim code via dfu in all versions, so that might provide a simpler alternative. 

- setup the device wifi credentials via serial
- trigger the device to enter DFU mode by switching to 14400 baud
- obtain the claim code from the cloud and use dfu to write the claim code to the DCT region

**Comment by monkbroc** [comment]
I'm closing this one because claiming over serial is part of `particle setup` now.
