### ISSUE TITLE
Line breaks are ignored in OS X terminal

### ISSUE THREAD

**Issue by osmithy** [spark/particle-cli#66]
When I compile using particle-cli in OS X terminal, errors are spewed out all in one giant line, with "\n" instead of line breaks. Is there a way to control the output such that the terminal will recognize the line breaks?

**Comment by emilyrose** [comment]
Hey @osmithy,

sorry to hear that you're having trouble. Could you give me a little more context? I'm having trouble picturing what's happening. Perhaps a screenshot or some terminal output if possible? Thanks!

**Comment by osmithy** [comment]
Totally! Here's a screenshot.
<img width="985" alt="screen shot 2015-07-15 at 10 06 46 am" src="https://cloud.githubusercontent.com/assets/13243398/8704662/3bdae0fa-2ad9-11e5-8e41-4529897aef31.png">

**Comment by monkbroc** [comment]
This is due to the difference in the API response for compile vs flash when there is a compilation error. @dmiddlecamp would have more insight.

**Comment by dmiddlecamp** [comment]
Hmm, this doesn't look nested to me, I think the CLI just isn't trying to pretty print the output

**Comment by osmithy** [comment]
Oh cool, it looks right when I use compile. Thanks for pointing that out! That really helps.

**Comment by monkbroc** [comment]
You're right @dmiddlecamp. My eyes didn't "parse" the JSON correctly. Thanks for commenting.

**Comment by monkbroc** [comment]
@emilyrose was busy yesterday! Thanks for all the work.

**Comment by emilyrose** [comment]
@monkbroc no no, thank *you*! :wink:
