### ISSUE TITLE
`keys doctor` and `flash --usb` report failure for the Photon even when successful

### ISSUE THREAD

**Issue by jnm2** [spark/particle-cli#68]
If I'm missing something obvious, please be kind. I looked at all the documentation I could find. I've done this successfully in the past with a local server and Cores.

When the Photon is in DFU mode and I run [`keys doctor`](https://github.com/spark/particle-cli#particle-keys-doctor), I get:

> Downloading to address = 0x00000022, size = 610
> Download        [=========================] 100%          610 bytes
> Download done.
> File downloaded successfully
> Error during download get_status
> Error saving key to device...
> Make sure your device is in DFU mode (blinking yellow), and that your computer is online.
> Error -

[`keys server`](https://github.com/spark/particle-cli#particle-keys-server) works just fine.

[`flash --usb tinker`](https://github.com/spark/particle-cli#flashing-a-known-app) gives:

> Downloading to address = 0x080a0000, size = 79996
> Download        [=========================] 100%        79996 bytes
> Download done.
> File downloaded successfully
> Error during download get_status
> Error writing firmware...

I relied on both these steps when I used to do Cores. As it is, I have not yet been successful at connecting a Photon to the local server.

As I understand it, I should execute:

 1. `particle keys server default_key.pub.pem SERVER-MACHINE-IP` (working)
 2. `particle keys doctor COREID` (broken)
 3. `particle serial wifi` (working)
 4. `particle core add COREID` (might be working?)

I'm stuck on step 2. I did a very similar sequence a while back when I had Cores. Am I doing this the wrong way?

**Comment by jnm2** [comment]
I just tried upgrading to [0.4.3](https://github.com/spark/firmware/releases/tag/0.4.3-rc2). `dfu-util -d 2b04:d006 -a 0 -s 0x8020000 -D system-part1-0.4.3-photon.bin` worked fine, and `dfu-util -d 2b04:d006 -a 0 -s 0x8060000:leave -D system-part2-0.4.3-photon.bin` resulted in the same error shown above.

I've also tried all three USB drivers from Zadig.

**Comment by brycekahle** [comment]
@jnm2 The `Error during download get_status` is not an actual error. `dfu-util` reports that even if the system part 2 flash was successful. We need to fix the flash command to not report failure in this case.

The breathing red is probably something related to your local cloud setup, possibly related to keys.

**Comment by brycekahle** [comment]
The `Error during download get_status` is something that has been addressed in the bootloader for version 0.4.9 of the firmware. I'm going to close this issue, but please reopen if you run into it again.
