### ISSUE TITLE
Fails silently when access token is expired

### ISSUE THREAD

**Issue by wgbartley** [spark/particle-cli#69]
It seems that any of the online commands will fail silently when the access token expires.  Wifi setup commands (`particle serial wifi`) works fine, but something like `particle subscribe mine` spits out the following and immediately goes back to command prompt.

```
Garretts-MacBook-Pro:Desktop garrett$ particle subscribe mine
Subscribing to all events from my personal stream (my devices only) 
Listening to: /v1/devices/events
Garretts-MacBook-Pro:Desktop garrett$
```

**Comment by brycekahle** [comment]
Thanks for the bug report @wgbartley. I'll look into storing refresh tokens and detecting this state automatically and grabbing a new token.

**Comment by dmiddlecamp** [comment]
I think some of the other api calls detect an expired session, it might also be nice to make sure we show the appropriate error here if our session is expired while we work on the refresh behavior.

**Comment by brycekahle** [comment]
Fixed with https://github.com/spark/particle-cli/commit/da1668ad862f1baaa4f6de911955f90b267319a9
