### ISSUE TITLE
wrong value for invalid_grant

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#71]
@dmiddlecamp,

while trying to fix another issue, i saw that the implementation for bad token check seems to be incorrect.

The server is returning `invalid_token` while the check is looking for `invalid_grant` at https://github.com/spark/particle-cli/blob/master/lib/ApiClient.js#L800

Can you confirm the actual response for invalid token?

Also, seems like the function `hasBadToken()` is called, but the return value is not checked so the bad token case is not caught. Related to: https://github.com/spark/particle-cli/issues/69

**Comment by dmiddlecamp** [comment]
Good question!  invalid_token can be returned for an expired token, invalid_grant can be returned when an auth code / user credentials / the refresh token / etc are invalid.  I wonder if something was updated API-side.  I suspect we should check for both?

**Comment by kennethlimcp** [comment]
Basically i replaced my access token in my profile with some random typed ones to simulate expired token which obviously identified as invalid and not expired. 

We should check for both though. I need to dig further into the other issue as well..
