### ISSUE TITLE
`particle serial info`

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#76]
Adding a command to retrieve the system information for the Photon and the Electron will be easily than getting people to open up a serial terminal and hit "s"

**Comment by zsup** [comment]
Agreed; would also be helpful to take the opportunity to make that info more human readable

**Comment by kennethlimcp** [comment]
definitely. :+1:

**Comment by emilyrose** [comment]
with the Electron it sounds like we'll also need to handle parsing additional information like IMEI/SIM card info.
