### ISSUE TITLE
No such file, when trying 

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#77]
It used to be a common tip for users to reflash tinker via CLI if something got a bit hairy, but recently it seems to have stopped working 
When trying `particle flash --usb tinker`, I get this
```
C:\Users\Andy>particle flash --usb tinker
Found DFU device 2b04:d006
checking file  binaries/photon_tinker.bin
running dfu-util -d 2b04:d006 -a 0 -i 0 -s 0x080A0000:leave -D binaries/photon_tinker.bin

Error writing firmware...Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "dfu-util -d 2b04:d006 -a 0 -i 0 -s 0x080A0000:leave -D binaries/photon_tinker.bin"
No such file or directory: Could not open file binaries/photon_tinker.bin for reading
```

And for the Core respectively.

**Comment by monkbroc** [comment]
I got that on Ubuntu as well a couple days ago and I just thought my particle-cli install was corrupted.

**Comment by kennethlimcp** [comment]
We need to have the last bits of the PR pulled in - https://github.com/spark/particle-cli/commit/5483ada0d0ce5a6ec6dbaf178ec92a87aa3e593f#diff-2d78dada12f5fa4f3183bc45f30f590cL87

**Comment by kennethlimcp** [comment]
Fixed here: https://github.com/spark/particle-cli/commit/1b60c14984bffc308436c83cef8b88bc0016d0d5

**Comment by emilyrose** [comment]
thanks again for the report @ScruffR, sorry about that!
