### ISSUE TITLE
extra slash at the end of configured apiUrl causes confusing issues / errors, can we detect this?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#8]
user error on my part, forgot not to add the extra slash at the end, can we catch this?

**Comment by kennethlimcp** [comment]
Something like checking the last char for the "/"?

**Comment by emilyrose** [comment]
@kennethlimcp yep! pretty much. super simple fix.

**Comment by kennethlimcp** [comment]
You or me? :smile:

**Comment by emilyrose** [comment]
Whoever gets to it first, I suppose!

**Comment by kennethlimcp** [comment]
Cool i also need to pull in my stale PR from **spark-cli** :scream:
