### ISSUE TITLE
[Proposal] particle serial terminal

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#85]
This is similar to `particle serial monitor` but user input will be passed to the device as well. It should be a single char passed each time a key is pressed.

**Comment by joegoggins** [comment]
:+1: this would be an extremely useful feature. It would be awesome if the command had an option that would open a serial connection to device, enter a character sequence, return the output to stdout, and exit.  Perhaps my feature request is a bit different than what Kenneth is describing, my use case is more like a generalized version of `particle identify` 

To contextualize my use case, here is an example task I'd use this feature for: Write a test case somewhere in our CI pipeline that would assert a device reports expected versions of things ala `particle serial command s > some.json` then read some.json and assert the system versions are set correctly.

**Comment by kennethlimcp** [comment]
`particle serial send xxx` ?

**Comment by joegoggins** [comment]
Perfect.

**Comment by monkbroc** [comment]
For `particle serial terminal`, a useful feature would be to reopen the serial port automatically after a device reset. It's a pain right now to use another terminal program that needs to be reopened whenever the device is reflashed. I end up missing the first few lines of output unless I put a big `delay` at the beginning of the user firmware...

**Comment by emilyrose** [comment]
would it also be useful if we allow users to specify whether they want each char sent immediately, or if they want to queue them up and then send on newline? This would be helpful against typos when playing with basic protocols that are newline terminated.

**Comment by technobly** [comment]
For some reason I thought `particle serial monitor` already did this... but as I'm finding out it does not?  Is `particle serial monitor` read (monitor) only?  When I type characters they are shown on the screen which is very misleading, as if they are being sent and echoed.

I would love to see `particle serial terminal` supersede `particle serial monitor` and depreciate monitor completely.  I realize monitor might be considered the GET request of serial if it's read only, and more of a safe serial terminal... however I think it would feel too confusing to have terminal and monitor and not being able to send characters doesn't seem like a mode we need for serial interaction.  If we did a command called `particle debug monitor` or even `particle debug` for a dedicated system debug output that might be better suited for read-only.

For `particle serial terminal` all echoing should be handled by the device, and all line terminations be entered by the user by default.  We could get fancy with options here `particle serial terminal <baud> <--echo> <--line-ending crlf|lfcr|cr|lf>` but I would not let this or the other features requested above keep us from implementing the default operation first :)

@brycekahle this is a valuable & much needed built-in feature for the CLI and totally gets :+1: :+1: of support.  Please let me know if you want help bringing this to life.

**Comment by ScruffR** [comment]
Since we now got the auto-reconnect feature `--follow` this would be the logical next step 😉

**Comment by ScruffR** [comment]
Please don't close that. I'd still want this to happen.
