### ISSUE TITLE
`particle firmware-version` command

### ISSUE THREAD

**Issue by joegoggins** [spark/particle-cli#95]
On the latest firmware (0.4.4), if you type "v" over serial to a Photon, you'll get something like like: "System Firmware: 0.4.4", it would be great to encapsulate this via the CLI with command like `particle firmware-version`. 

Additionally, if you type "s" over serial to a Photon, you'll get a bunch of .json illustrating the detailed versions and dependencies information. It would be cool to expose this detailed information via a `--details` switch to the `particle firmware-version` command as pretty json. This switch would also make a reference to the documentation that helps decypher this detailed info.

This feature enhancement is related to #85, I'd vote to build this one first, and then generalize it later to accommodate to the other broader `particle serial terminal` feature proposal.

**Comment by kennethlimcp** [comment]
@joegoggins suggesting `particle device version` with alias `particle device v` for this under the verb **device** command. Sounds good?

**Comment by dmiddlecamp** [comment]
can we just include this as part of `identify` ?

**Comment by kennethlimcp** [comment]
`particle identify`? Hmmm... How should we format all of them properly as one data set then? JSON?

**Comment by dmiddlecamp** [comment]
nah, just pretty output, for example:

```
Your DeviceID is: abc123
Your system firmware version is: 0.4.4
```

**Comment by kennethlimcp** [comment]
But `s` is not pretty... ^^ settles `i` and `v`

**Comment by dmiddlecamp** [comment]
I imagine we'll be adding 'system-firmware version' to the device attributes endpoint on the API in the next sprint or two, as well as the raw version info for the system-parts / platforms.  I think that will help parse the module json client-side if needed as well.

**Comment by kennethlimcp** [comment]
We should get that info off the device as much as possible for accuracy? Like i did `particle update` and i want to check immediately so might be good to just pull off serial instead of relying on cloud info
