### ISSUE TITLE
feature idea - 'particle list [online/offline/device-type/device-name]'

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#96]
I'm finding I just want to see what devices are online, or see my photons, or get the info for a specific device, what if we could run:

`particle list online`

and that would filter the list?  Same thing for offline, device type or device name, thoughts?

**Comment by joegoggins** [comment]
+1 , great suggestion! Several scripts I've written achieve this functionality via `particle list | grep "online"`, which is dumb and omits useful information (variables + function details). This proposed feature would be a great and welcome replacement for that.
